In [507]:
# Start with the CFS (2017)
import pyxlsb
import pandas as pd
cfs_path = '/Users/jeffreyohl/Dropbox/SpatialW25/BigDataFiles/pset2/CFS/'
cfs_mapping_path = "/Users/jeffreyohl/Dropbox/SpatialW25/BigDataFiles/pset2/Mapping Files/CFS_sector_aggregation.xlsx"
wiod_path = "/Users/jeffreyohl/Dropbox/SpatialW25/BigDataFiles/pset2/WIOD/WIOT2014_Nov16_ROW.xlsb"
wiod_mapping_sector_path = "/Users/jeffreyohl/Dropbox/SpatialW25/BigDataFiles/pset2/Mapping Files/WIOD_sector_aggregation.xlsx"
out_folder = "/Users/jeffreyohl/Dropbox/SpatialW25/BigDataFiles/pset2/X_in_j/"
out_folder_IO = '/Users/jeffreyohl/Dropbox/SpatialW25/BigDataFiles/pset2/IO/'
out_folder_gamma = '/Users/jeffreyohl/Dropbox/SpatialW25/BigDataFiles/pset2/gamma/'

out_folder_GO = '/Users/jeffreyohl/Dropbox/SpatialW25/BigDataFiles/pset2/GO/'
countries_path = "/Users/jeffreyohl/Dropbox/SpatialW25/BigDataFiles/pset2/Mapping Files/WIOD_country_codes.csv"

intial_emp = "/Users/jeffreyohl/Dropbox/SpatialW25/BigDataFiles/pset2/dummy data/L0_initial.csv"

In [350]:
country = pd.read_csv(countries_path)

In [351]:
country.head()

  Code CountryLong  Country
0  AUS   Australia        1
1  AUT     Austria        2
2  BEL     Belgium        3
3  BGR    Bulgaria        4
4  BRA      Brazil        5

In [352]:
country_map = country.set_index('Code')['Country'].to_dict()

# WIOD 2014

In [353]:


# ------------------------------
# 1) Read the matrix from Excel
# ------------------------------
# - skiprows=4 so that the first row we read is row 5 of the sheet
# - header=[0,1] means: the first two rows we read become a 2-level column header
#   (row 5 is level 0: "ImportingCountry", row 6 is level 1: "ImportingIndustry")
# - index_col=[2,3] means: use columns C and D (zero-based: 2 and 3) as the row index
#   (ExportingCountry, ExportingIndustry)
df = pd.read_excel(
    wiod_path,
    sheet_name="2014",
    skiprows=4,        # Adjust if you have more or fewer label rows
    header=[0, 1],     # Row 5 => upper col labels, Row 6 => lower col labels
    index_col=[2, 3],  # Column C => ExportingCountry, Column D => ExportingIndustry
    # usecols="C:ZZ",  # Optionally restrict columns if needed
)

# By default, pandas will name the two column levels something like (None, None).
# We can rename them:
df.columns.names = ["ImportingCountry", "ImportingIndustry"]
df.index.names = ["ExportingCountry", "ExportingIndustry"]




# df is now a 2D table whose:
#   - row index = (ExportingCountry, ExportingIndustry)
#   - columns   = (ImportingCountry, ImportingIndustry)
#   - cell values = trade flows (or I/O flows).

# ------------------------------
# 2) Reshape from wide to long
# ------------------------------
# We "stack" over the two column levels:
df_long = df.stack(level=[0, 1]).reset_index()

# The result has columns:
#   ["ExportingCountry", "ExportingIndustry", "ImportingCountry", "ImportingIndustry", 0]
# Rename the last one to "Value" (or something relevant).
df_long.columns = [
    "ExportingCountry",
    "ExportingIndustry",
    "ImportingCountry",
    "ImportingIndustry",
    "Value",
]

# ------------------------------
# 3) Filter out invalid industries (optional)
# ------------------------------
# If valid industries are r1..r56 for exporting and c1..c56 for importing:
valid_r = [f"r{i}" for i in range(1, 57)]
valid_c = [f"c{i}" for i in range(1, 57)]

df_long = df_long[
    df_long["ExportingIndustry"].isin(valid_r)
    & df_long["ImportingIndustry"].isin(valid_c)
]

# ------------------------------
# 4) Collapse certain countries
# ------------------------------
# E.g. CHE, HRV, LUX, LVA, MLT, NOR => "ROW"
row_countries = ["CHE", "HRV", "LUX", "LVA", "MLT", "NOR"]

df_long["ExportingCountry"] = df_long["ExportingCountry"].where(
    ~df_long["ExportingCountry"].isin(row_countries), 
    "ROW"
)
df_long["ImportingCountry"] = df_long["ImportingCountry"].where(
    ~df_long["ImportingCountry"].isin(row_countries), 
    "ROW"
)

# ------------------------------
# 5) Summation / Aggregation
# ------------------------------
df_agg = df_long.groupby(
    ["ExportingCountry", "ExportingIndustry", 
     "ImportingCountry", "ImportingIndustry"],
    as_index=False
)["Value"].sum()


print(df_agg.head(15))

/var/folders/g9/ggrmf_5j6tx4rv5qdhs0slq40000gn/T/ipykernel_45649/3192670138.py:35: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df_long = df.stack(level=[0, 1]).reset_index()

   ExportingCountry ExportingIndustry ImportingCountry ImportingIndustry  \
0               AUS                r1              AUS                c1
1               AUS                r1              AUS               c10
2               AUS                r1              AUS               c11
3               AUS                r1              AUS               c12
4               AUS                r1              AUS               c13
5               AUS                r1              AUS               c14
6               AUS                r1              AUS               c15
7               AUS                r1              AUS               c16
8               AUS                r1              AUS               c17
9               AUS                r1              AUS               c18
10              AUS                r1              AUS               c19
11              AUS                r1              AUS                c2
12              AUS                r1              AUS               c20
13              AUS                r1              AUS               c21
14              AUS                r1              AUS               c22

           Value
0   12924.179691
1       0.226825
2      86.721589
3     109.147573
4     147.252719
5       5.054258
6       8.126751
7       6.341826
8       0.340432
9       1.124518
10      2.308996
11    112.454221
12       2.49353
13      2.514789
14      9.451747

In [354]:
df_agg.columns

Index(['ExportingCountry', 'ExportingIndustry', 'ImportingCountry',
       'ImportingIndustry', 'Value'],
      dtype='object')

In [355]:
df_agg

,ExportingCountry,ExportingIndustry,ImportingCountry,ImportingIndustry,Value
0,AUS,r1,AUS,c1,12924.179691
1,AUS,r1,AUS,c10,0.226825
2,AUS,r1,AUS,c11,86.721589
3,AUS,r1,AUS,c12,109.147573
4,AUS,r1,AUS,c13,147.252719
...,...,...,...,...,...
4528379,USA,r9,USA,c56,0.0
4528380,USA,r9,USA,c6,743.552862
4528381,USA,r9,USA,c7,75.372114
4528382,USA,r9,USA,c8,208.748822
4528383,USA,r9,USA,c9,1436.794888

In [356]:
country_map

{'AUS': 1,
 'AUT': 2,
 'BEL': 3,
 'BGR': 4,
 'BRA': 5,
 'CAN': 6,
 'CHN': 7,
 'CYP': 8,
 'CZE': 9,
 'DNK': 10,
 'EST': 11,
 'FIN': 12,
 'FRA': 13,
 'DEU': 14,
 'GRC': 15,
 'HUN': 16,
 'IND': 17,
 'IDN': 18,
 'ITA': 19,
 'IRL': 20,
 'JPN': 21,
 'LTU': 22,
 'MEX': 23,
 'NLD': 24,
 'POL': 25,
 'PRT': 26,
 'ROU': 27,
 'RUS': 28,
 'ESP': 29,
 'SVK': 30,
 'SVN': 31,
 'KOR': 32,
 'SWE': 33,
 'TWN': 34,
 'TUR': 35,
 'GBR': 36,
 'ROW': 37,
 'USA': 38}

In [357]:
country_map

{'AUS': 1,
 'AUT': 2,
 'BEL': 3,
 'BGR': 4,
 'BRA': 5,
 'CAN': 6,
 'CHN': 7,
 'CYP': 8,
 'CZE': 9,
 'DNK': 10,
 'EST': 11,
 'FIN': 12,
 'FRA': 13,
 'DEU': 14,
 'GRC': 15,
 'HUN': 16,
 'IND': 17,
 'IDN': 18,
 'ITA': 19,
 'IRL': 20,
 'JPN': 21,
 'LTU': 22,
 'MEX': 23,
 'NLD': 24,
 'POL': 25,
 'PRT': 26,
 'ROU': 27,
 'RUS': 28,
 'ESP': 29,
 'SVK': 30,
 'SVN': 31,
 'KOR': 32,
 'SWE': 33,
 'TWN': 34,
 'TUR': 35,
 'GBR': 36,
 'ROW': 37,
 'USA': 38}

In [358]:
df_agg['ExportingCountry'] = df_agg['ExportingCountry'].map(country_map)
df_agg['ImportingCountry'] = df_agg['ImportingCountry'].map(country_map)

In [359]:
df_agg = df_agg.to_csv(out_folder + "long_fix_countries.csv")

In [360]:
df_agg = pd.read_csv(out_folder + "long_fix_countries.csv")

In [361]:
df_agg

,Unnamed: 0,ExportingCountry,ExportingIndustry,ImportingCountry,ImportingIndustry,Value
0,0,1,r1,1,c1,12924.179691
1,1,1,r1,1,c10,0.226825
2,2,1,r1,1,c11,86.721589
3,3,1,r1,1,c12,109.147573
4,4,1,r1,1,c13,147.252719
...,...,...,...,...,...,...
4528379,4528379,38,r9,38,c56,0.000000
4528380,4528380,38,r9,38,c6,743.552862
4528381,4528381,38,r9,38,c7,75.372114
4528382,4528382,38,r9,38,c8,208.748822
4528383,4528383,38,r9,38,c9,1436.794888

In [362]:
mapping = pd.read_excel(wiod_mapping_sector_path)

In [363]:
%pip install openpyxl
import openpyxl

Requirement already satisfied: openpyxl in /Users/jeffreyohl/miniconda3/envs/ipopt_env/lib/python3.11/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Users/jeffreyohl/miniconda3/envs/ipopt_env/lib/python3.11/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [364]:
# 1) Build lookup dictionaries from your ‘mapping’ dataframe
out_map = mapping.set_index('output_code')['OrderExcldNon'].to_dict()
in_map  = mapping.set_index('input_code')['OrderExcldNon'].to_dict()
df_agg_sector_fix = df_agg.copy()
# 2) Map the old codes in df_agg to the new “Order in CDP 2019”
df_agg_sector_fix['ExportingIndustry'] = df_agg_sector_fix['ExportingIndustry'].map(out_map)
df_agg_sector_fix['ImportingIndustry'] = df_agg_sector_fix['ImportingIndustry'].map(in_map)

# 3) Drop rows where either mapped industry is NaN
df_agg_sector_fix = df_agg_sector_fix.dropna(subset=['ExportingIndustry','ImportingIndustry'])

# 4) Collapse (aggregate) non-unique rows, for example by summing 'Value'
df_agg_sector_fix = df_agg_sector_fix.groupby(
    ['ExportingCountry','ExportingIndustry','ImportingCountry','ImportingIndustry'],
    as_index=False
)['Value'].sum()

In [365]:
# For example, save to CSV
df_agg_sector_fix.to_csv(out_folder+ "long_fix_countries_and_sectors.csv", index=False)

In [366]:
# For example, save to CSV
df_agg_sector_fix =pd.read_csv(out_folder+ "long_fix_countries_and_sectors.csv")

In [367]:
df_agg_sector_fix

,ExportingCountry,ExportingIndustry,ImportingCountry,ImportingIndustry,Value
0,1,1.0,1,1.0,10851.759013
1,1,1.0,1,2.0,262.228559
2,1,1.0,1,3.0,40.510798
3,1,1.0,1,4.0,2.897519
4,1,1.0,1,5.0,352.067899
...,...,...,...,...,...
698891,38,22.0,38,18.0,214761.185588
698892,38,22.0,38,19.0,25490.798838
698893,38,22.0,38,20.0,241208.476296
698894,38,22.0,38,21.0,116928.130124
698895,38,22.0,38,22.0,826747.505531

In [368]:
us_code = country_map['USA']

In [369]:
us_code

38

In [370]:
domestic_usa_trade = df_agg_sector_fix[
    (df_agg_sector_fix['ExportingCountry'] == us_code) & 
    (df_agg_sector_fix['ImportingCountry'] == us_code )
]

# Group by exporting industry and sum Value
domestic_expenditure = domestic_usa_trade.groupby('ExportingIndustry', as_index=False)['Value'].sum()

In [371]:
domestic_expenditure

    ExportingIndustry         Value
0                 1.0  3.702758e+05
1                 2.0  5.021600e+04
2                 3.0  2.875896e+05
3                 4.0  3.924727e+05
4                 5.0  3.776814e+05
5                 6.0  1.617610e+05
6                 7.0  9.119060e+04
7                 8.0  5.297387e+05
8                 9.0  1.214166e+05
9                10.0  2.010416e+05
10               11.0  2.779642e+05
11               12.0  8.313151e+04
12               13.0  8.805743e+05
13               14.0  2.239603e+05
14               15.0  6.046541e+05
15               16.0  8.396479e+05
16               17.0  1.158419e+06
17               18.0  8.392791e+05
18               19.0  4.512257e+04
19               20.0  6.107469e+04
20               21.0  1.982918e+05
21               22.0  2.857253e+06

In [372]:
import pandas as pd

# Replace 'your_file.dta' with the path to your .dta file
cfs_2017 = pd.read_stata(cfs_path + 'states_ind_bilateral_trade2017.dta')

In [373]:
cfs_2017['origin'] = cfs_2017['origin'].replace('District of Columbia', 'Virginia')
cfs_2017['dest'] = cfs_2017['dest'].replace('District of Columbia', 'Virginia')

In [374]:
cfs_2017['origin'].unique()

array(['Arkansas', 'South Carolina', 'Maryland', 'Delaware', 'Wisconsin',
       'Massachusetts', 'Iowa', 'Colorado', 'Montana', 'Louisiana',
       'Kentucky', 'Idaho', 'New Mexico', 'Florida', 'Washington',
       'Hawaii', 'Texas', 'Missouri', 'California', 'Alaska', 'Utah',
       'Arizona', 'Nevada', 'Wyoming', 'Illinois', 'North Dakota',
       'Indiana', 'Georgia', 'Connecticut', 'New York', 'Mississippi',
       'North Carolina', 'Maine', 'Oklahoma', 'Alabama', 'Michigan',
       'Virginia', 'Nebraska', 'South Dakota', 'New Hampshire', 'Vermont',
       'Pennsylvania', 'West Virginia', 'Ohio', 'Kansas', 'New Jersey',
       'Minnesota', 'Oregon', 'Tennessee', 'Rhode Island',
       'United States'], dtype=object)

In [375]:
cfs_2017 = cfs_2017[cfs_2017['origin_abrv'] != 'USA']


cfs_2017 = cfs_2017[cfs_2017['dest_abrv'] != 'USA']

# Display the first few rows of the dataframe
cfs_2017.head()

cfs_2017.to_csv(cfs_path + 'states_ind_bilateral_trade2017.csv')

In [376]:
cfs_2017

,origin,origin_abrv,dest,dest_abrv,year,naics2012,naics2012_ttl,naics2012_f,val,ton,tmile,avgmile,d_state_origin,d_state_dest
0,Arkansas,AR,Alabama,AL,2017,423,"Merchant wholesalers, durable goods",,369,252,104,405,1,1
1,South Carolina,SC,Alabama,AL,2017,333,Machinery manufacturing,,83,4,2,618,1,1
2,Maryland,MD,Alabama,AL,2017,423,"Merchant wholesalers, durable goods",,110,0,0,830,1,1
3,Delaware,DE,Alabama,AL,2017,4239,Miscellaneous durable goods merchant wholesalers,,0,0,0,848,1,1
4,Wisconsin,WI,Alabama,AL,2017,4236,Household appliances and electrical and electr...,,0,0,0,798,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101505,Colorado,CO,Wyoming,WY,2017,4238,"Machinery, equipment, and supplies merchant wh...",,156,0,2,277,1,1
101506,Missouri,MO,Wyoming,WY,2017,327,Nonmetallic mineral product manufacturing,,0,0,0,0,1,1
101507,Arkansas,AR,Wyoming,WY,2017,31-33,Manufacturing,,86,0,0,1224,1,1
101508,Maryland,MD,Wyoming,WY,2017,42,Wholesale trade,,0,0,0,1826,1,1
101509,Tennessee,TN,Wyoming,WY,2017,337,Furniture and related product manufacturing,,2,1,1,1542,1,1

In [377]:
cfs_2017 = cfs_2017[['dest', 'origin', 'naics2012', 'val']]

# some summary stats

In [378]:
# Group by naics2012, sum the val column, and sort in descending order
cfs_2017 = cfs_2017[cfs_2017['naics2012'] != '00']
result = cfs_2017.groupby('naics2012')['val'].sum().sort_values(ascending=False)

In [379]:
cfs_mapping = pd.read_excel(cfs_mapping_path)

In [380]:
cfs_mapping['naics2012'] = cfs_mapping['naics2012'].astype(str)
cfs_2017['naics2012'] = cfs_2017['naics2012'].astype(str)

# Create a mapping dictionary from cfs_mapping
mapping_dict = dict(zip(cfs_mapping['naics2012'], cfs_mapping['CDP order']))

# Map the 'naics_2012' column in cfs_2017 to a new 'CDP order' column
cfs_2017['CDP order'] = cfs_2017['naics2012'].map(mapping_dict)

In [381]:
cfs_2017_collapsed = cfs_2017.groupby(['dest', 'origin', 'CDP order'], as_index=False)['val'].sum()

In [382]:
cfs_2017['naics2012'].unique()

array(['423', '333', '4239', '4236', '337', '4237', '324', '339', '4249',
       '325', '4541', '42', '326', '424', '321', '4241', '335', '4243',
       '312', '4233', '4234', '316', '313', '334', '4232', '4244', '331',
       '336', '4245', '4931', '4231', '31-33', '5111', '327', '332',
       '315', '4242', '323', '4238', '4247', '551114', '4235', '212',
       '311', '4248', '322', '45431', '4246', '314'], dtype=object)

In [383]:
cfs_2017_collapsed

          dest   origin  CDP order    val
0      Alabama  Alabama        1.0   4427
1      Alabama  Alabama        2.0    189
2      Alabama  Alabama        3.0   3160
3      Alabama  Alabama        4.0   4306
4      Alabama  Alabama        5.0   2269
...        ...      ...        ...    ...
28965  Wyoming  Wyoming        9.0     72
28966  Wyoming  Wyoming       10.0      4
28967  Wyoming  Wyoming       11.0      0
28968  Wyoming  Wyoming       12.0   4406
28969  Wyoming  Wyoming       13.0  11921

[28970 rows x 4 columns]

In [384]:
import pandas as pd

# Suppose your DataFrame is called df and has columns:
#   ['dest_abrv', 'origin_abrv', 'CDP order', 'val']
# Make sure df is read in as a DataFrame.

# Get the sorted list of all states
all_states = sorted(set(cfs_2017_collapsed['dest']) | set(cfs_2017_collapsed['origin']))

# Get all unique sectors
cdp_orders = sorted(cfs_2017_collapsed['CDP order'].unique())

# Dictionary to store the resulting 50x50 share matrices per sector
trade_share_matrices = {}

for sector in cdp_orders:
    # Filter to this sector
    sector_df = cfs_2017_collapsed[cfs_2017_collapsed['CDP order'] == sector].copy()

    # Pivot so that rows=origin, columns=destination, values=val
    pivoted = sector_df.pivot_table(
        index='origin',
        columns='dest',
        values='val',
        aggfunc='sum',
        fill_value=0
    )

    # Reindex to ensure we have all 50 states as rows & columns (fill missing with 0)
    pivoted = pivoted.reindex(index=all_states, columns=all_states, fill_value=0)

    # Column sums (each destination state's total expenditure in this sector)
    col_sums = pivoted.sum(axis=0)

    # Divide each column by its sum to get shares; fill any 0/0 with 0
    shares = pivoted.div(col_sums, axis=1).fillna(0)

    # Store in a dictionary keyed by the sector (CDP order)
    trade_share_matrices[sector] = shares

# Now trade_share_matrices[sector] is your 50x50 DataFrame of shares 
# for that particular sector. Each column sums to 1.

In [385]:
trade_share_matrices

{np.float64(1.0): dest             Alabama    Alaska   Arizona  Arkansas  California  Colorado  \
 origin
 Alabama         0.379089  0.000000  0.007258  0.014605    0.003261  0.008314
 Alaska          0.000000  0.948381  0.000388  0.000000    0.000396  0.000000
 Arizona         0.000000  0.000000  0.472241  0.000648    0.014096  0.006176
 Arkansas        0.000000  0.000000  0.015791  0.447114    0.007238  0.015045
 California      0.035194  0.004223  0.195700  0.020200    0.666872  0.073719
 Colorado        0.001456  0.000000  0.006538  0.000000    0.014637  0.526249
 Connecticut     0.000514  0.000000  0.000000  0.000000    0.000183  0.000079
 Delaware        0.000514  0.000000  0.000111  0.000000    0.000914  0.000000
 Florida         0.014129  0.000000  0.001884  0.003180    0.003391  0.001504
 Georgia         0.121596  0.000000  0.002826  0.027032    0.006857  0.007918
 Hawaii          0.000000  0.000000  0.000000  0.000000    0.000617  0.000000
 Idaho           0.001199  0.000000  0.009863  0.000000    0.008374  0.018370
 Illinois        0.014044  0.000000  0.013741  0.013722    0.021890  0.013461
 Indiana         0.025176  0.000000  0.005762  0.013722    0.006697  0.004513
 Iowa            0.021237  0.000000  0.043661  0.025677    0.013067  0.027160
 Kansas          0.012417  0.000000  0.010694  0.008304    0.014697  0.030406
 Kentucky        0.026460  0.000000  0.010527  0.007420    0.008480  0.009502
 Louisiana       0.023634  0.000000  0.004377  0.004829    0.003497  0.008077
 Maine           0.000000  0.000000  0.000000  0.000000    0.000069  0.000000
 Maryland        0.000000  0.000000  0.000554  0.000000    0.000008  0.000000
 Massachusetts   0.000343  0.000000  0.000776  0.000118    0.001699  0.000079
 Michigan        0.003511  0.000000  0.008865  0.000000    0.005593  0.000238
 Minnesota       0.002740  0.000000  0.016401  0.008481    0.012755  0.014649
 Mississippi     0.053434  0.000000  0.003768  0.036160    0.003817  0.005384
 Missouri        0.015756  0.000000  0.013907  0.110777    0.016960  0.027635
 Montana         0.000000  0.000000  0.000000  0.000000    0.000000  0.000633
 Nebraska        0.006080  0.000000  0.008754  0.024323    0.016244  0.030169
 Nevada          0.000000  0.000000  0.002327  0.000000    0.009014  0.006414
 New Hampshire   0.000000  0.000000  0.000000  0.000000    0.000922  0.000000
 New Jersey      0.004624  0.009385  0.000388  0.001178    0.004869  0.000475
 New Mexico      0.001199  0.000000  0.000000  0.000000    0.001158  0.005780
 New York        0.007107  0.000000  0.000000  0.000883    0.003208  0.003484
 North Carolina  0.040846  0.000000  0.001441  0.023675    0.005638  0.016866
 North Dakota    0.000000  0.000000  0.003269  0.000000    0.000922  0.001267
 Ohio            0.021065  0.000000  0.007037  0.026914    0.009478  0.008077
 Oklahoma        0.002826  0.000000  0.007979  0.055300    0.006629  0.013778
 Oregon          0.000000  0.022994  0.008090  0.000000    0.013936  0.003484
 Pennsylvania    0.007107  0.000000  0.003546  0.005654    0.004503  0.002930
 Rhode Island    0.000856  0.000000  0.000000  0.000000    0.000107  0.000000
 South Carolina  0.012245  0.000000  0.000000  0.005771    0.003139  0.000000
 South Dakota    0.000000  0.000000  0.000000  0.001355    0.001234  0.000000
 Tennessee       0.089313  0.000000  0.000000  0.033451    0.005097  0.003484
 Texas           0.030313  0.000000  0.051917  0.059011    0.022492  0.036503
 Utah            0.000856  0.000000  0.033965  0.005065    0.019185  0.041096
 Vermont         0.000000  0.000000  0.000000  0.000000    0.000305  0.000000
 Virginia        0.008306  0.000000  0.002715  0.003239    0.002720  0.007364
 Washington      0.000856  0.015016  0.012190  0.000000    0.018583  0.004989
 West Virginia   0.000343  0.000000  0.000000  0.000000    0.000046  0.000079
 Wisconsin       0.013615  0.000000  0.010694  0.012132    0.014393  0.014015
 Wyoming         0.000000  0.000000  0.000055  0.000059    0.000114  0.000633

 dest            Connecticut  Delaware   Florida   Georgia  ...  South Dakota  \
 origin                                                     ...
 Alabama            0.000655  0.000000  0.029484  0.051794  ...      0.000000
 Alaska             0.000000  0.000000  0.000080  0.000000  ...      0.000000
 Arizona            0.000131  0.000000  0.001447  0.000000  ...      0.000000
 Arkansas           0.005243  0.000000  0.003758  0.018271  ...      0.000000
 California         0.033425  0.000000  0.041885  0.025620  ...      0.000000
 Colorado           0.000000  0.000000  0.000000  0.002580  ...      0.023427
 Connecticut        0.435575  0.000000  0.000322  0.000000  ...      0.000000
 Delaware           0.012321  0.541154  0.001206  0.003226  ...      0.000000
 Florida            0.020317  0.000000  0.471430  0.037463  ...      0.000000
 Georgia            0.006685  0.000000  0.085499  0.352994  ...      0.000000
 Hawaii             0.000000  0.000000  0.000000  0.000000  ...      0.000000
 Idaho              0.000000  0.000000  0.002251  0.003917  ...      0.000000
 Illinois           0.001835  0.005203  0.028017  0.044167  ...      0.039504
 Indiana            0.007340  0.009934  0.011496  0.019008  ...      0.000000
 Iowa               0.003801  0.000000  0.007778  0.014446  ...      0.073496
 Kansas             0.010617  0.000000  0.016541  0.019953  ...      0.000000
 Kentucky           0.008127  0.013718  0.018993  0.025851  ...      0.005053
 Louisiana          0.000000  0.000000  0.005427  0.005622  ...      0.000459
 Maine              0.000000  0.000946  0.000261  0.000438  ...      0.000000
 Maryland           0.016254  0.091296  0.001146  0.002765  ...      0.000000
 Massachusetts      0.115480  0.006623  0.006512  0.003963  ...      0.000919
 Michigan           0.000131  0.000946  0.007075  0.017626  ...      0.000000
 Minnesota          0.009700  0.000000  0.007316  0.009009  ...      0.070740
 Mississippi        0.000000  0.008988  0.008863  0.008387  ...      0.000000
 Missouri           0.000000  0.000000  0.007316  0.015160  ...      0.020211
 Montana            0.000000  0.000000  0.000000  0.000000  ...      0.005512
 Nebraska           0.010355  0.000000  0.016702  0.010806  ...      0.014240
 Nevada             0.000000  0.000000  0.000000  0.000207  ...      0.000000
 New Hampshire      0.008127  0.000000  0.001407  0.000000  ...      0.000000
 New Jersey         0.041683  0.040681  0.011657  0.010760  ...      0.000000
 New Mexico         0.000000  0.000000  0.001447  0.000000  ...      0.000000
 New York           0.060558  0.021287  0.014792  0.011474  ...      0.000000
 North Carolina     0.014943  0.082308  0.038288  0.028408  ...      0.000000
 North Dakota       0.000000  0.000000  0.001347  0.001843  ...      0.028020
 Ohio               0.028444  0.007569  0.010190  0.022395  ...      0.000000
 Oklahoma           0.000000  0.000000  0.001970  0.004055  ...      0.000000
 Oregon             0.000786  0.000473  0.001970  0.002995  ...      0.003215
 Pennsylvania       0.086512  0.117786  0.017707  0.022579  ...      0.000459
 Rhode Island       0.004981  0.001419  0.000000  0.000000  ...      0.000000
 South Carolina     0.004457  0.003311  0.012883  0.019976  ...      0.000000
 South Dakota       0.000000  0.000000  0.000603  0.001244  ...      0.584290
 Tennessee          0.003015  0.000000  0.027233  0.079879  ...      0.000000
 Texas              0.000000  0.004730  0.037685  0.036703  ...      0.005053
 Utah               0.000262  0.000000  0.001950  0.004401  ...      0.002297
 Vermont            0.001311  0.000000  0.000281  0.000415  ...      0.000000
 Virginia           0.018875  0.029328  0.014270  0.018501  ...      0.000000
 Washington         0.001704  0.000000  0.003236  0.003318  ...      0.000000
 West Virginia      0.000000  0.000000  0.000080  0.000968  ...      0.000000
 Wisconsin          0.026347  0.012299  0.020199  0.036818  ...      0.119890
 Wyoming            0.000000  0.000000  0.000000  0.000000  ...      0.003215

 dest            Tennessee     Texas      Utah   Vermont  Virginia  Washington  \
 origin
 Alabama          0.016919  0.007110  0.004663  0.000000  0.002193    0.000637
 Alaska           0.000000  0.000187  0.000000  0.001128  0.000000    0.067688
 Arizona          0.001097  0.005242  0.026578  0.000000  0.000000    0.001791
 Arkansas         0.028986  0.011991  0.022848  0.000000  0.001409    0.002825
 California       0.042319  0.047882  0.153968  0.027637  0.014878    0.139674
 Colorado         0.006540  0.015657  0.028817  0.000000  0.001305    0.009590
 Connecticut      0.000506  0.000654  0.003824  0.029893  0.000626    0.000000
 Delaware         0.000506  0.002102  0.002798  0.009588  0.003210    0.000875
 Florida          0.010590  0.013345  0.000653  0.007332  0.005377    0.001592
 Georgia          0.065736  0.020199  0.002425  0.000000  0.013468    0.002427
 Hawaii           0.000000  0.000012  0.000000  0.000000  0.000026    0.000040
 Idaho            0.002447  0.005523  0.083932  0.000000  0.000835    0.020414
 Illinois         0.026750  0.024344  0.019677  0.007332  0.013599    0.007879
 Indiana          0.022193  0.019639  0.007274  0.000000  0.014251    0.006924
 Iowa             0.014472  0.032669  0.021729  0.020869  0.014565    0.027338
 Kansas           0.029577  0.033509  0.014362  0.000000  0.003498    0.002348
 Kentucky         0.050631  0.011547  0.009512  0.014100  0.017331    0.006327
 Louisiana        0.009071  0.013591  0.003730  0.000000  0.000183    0.000597
 Maine            0.000802  0.000000  0.000000  0.002256  0.000183    0.000000
 Maryland         0.004937  0.000000  0.000000  0.000000  0.015374    0.000000
 Massachusetts    0.000000  0.002440  0.000000  0.035533  0.000679    0.000358
 Michigan         0.016202  0.010380  0.019584  0.000000  0.003759    0.001393
 Minnesota        0.014556  0.013030  0.023967  0.007896  0.004463    0.012177
 Mississippi      0.007890  0.006900  0.000000  0.000000  0.000731    0.001273
 Missouri         0.011097  0.024402  0.010072  0.011844  0.002845    0.003701
 Montana          0.000000  0.000023  0.003824  0.000000  0.000000    0.002865
 Nebraska         0.011983  0.027111  0.018838  0.000000  0.001723    0.020175
 Nevada           0.001941  0.000525  0.006994  0.001128  0.000313    0.004775
 New Hampshire    0.000000  0.000747  0.000933  0.029893  0.000104    0.000000
 New Jersey       0.000802  0.007449  0.000000  0.006768  0.005873    0.005133
 New Mexico       0.004768  0.010006  0.009979  0.000000  0.000000    0.000000
 New York         0.008481  0.006363  0.003544  0.017484  0.010676    0.000517
 North Carolina   0.093836  0.010111  0.002425  0.019177  0.076582    0.012296
 North Dakota     0.002869  0.004472  0.001306  0.000000  0.001175    0.005491
 Ohio             0.042867  0.011337  0.023314  0.000000  0.025475    0.003900
 Oklahoma         0.008101  0.021775  0.012776  0.000000  0.000444    0.004974
 Oregon           0.000000  0.002744  0.030775  0.000000  0.000339    0.089813
 Pennsylvania     0.010632  0.004822  0.047841  0.025945  0.071649    0.001791
 Rhode Island     0.000000  0.000304  0.000000  0.000000  0.000000    0.000000
 South Carolina   0.000000  0.003946  0.009232  0.000000  0.003680    0.001313
 South Dakota     0.004135  0.002627  0.000000  0.000000  0.001253    0.000875
 Tennessee        0.333699  0.009002  0.000000  0.000000  0.012346    0.001671
 Texas            0.043922  0.519358  0.034039  0.000000  0.007308    0.013370
 Utah             0.000000  0.005219  0.255805  0.000000  0.000000    0.018384
 Vermont          0.004050  0.000269  0.000000  0.683587  0.000000    0.000000
 Virginia         0.006877  0.004635  0.012870  0.003948  0.629724    0.000000
 Washington       0.002194  0.005558  0.025926  0.000000  0.001096    0.493951
 West Virginia    0.000970  0.000000  0.000000  0.000000  0.003941    0.000000
 Wisconsin        0.034049  0.019066  0.037863  0.036661  0.011511    0.000836
 Wyoming          0.000000  0.000175  0.001306  0.000000  0.000000    0.000000

 dest            West Virginia  Wisconsin   Wyoming
 origin
 Alabama              0.011168   0.002487  0.000000
 Alaska               0.000000   0.000053  0.000000
 Arizona              0.000000   0.003610  0.000000
 Arkansas             0.000000   0.007435  0.000000
 California           0.011168   0.050600  0.138718
 Colorado             0.000000   0.008799  0.055312
 Connecticut          0.000000   0.000000  0.000000
 Delaware             0.000000   0.001498  0.000000
 Florida              0.000000   0.002888  0.000000
 Georgia              0.053807   0.006847  0.020193
 Hawaii               0.000000   0.000000  0.000000
 Idaho                0.000000   0.000000  0.071993
 Illinois             0.009137   0.052874  0.000000
 Indiana              0.000000   0.015057  0.012291
 Iowa                 0.000000   0.049129  0.143108
 Kansas               0.000000   0.013078  0.000000
 Kentucky             0.016244   0.005376  0.000000
 Louisiana            0.000000   0.000615  0.000000
 Maine                0.000000   0.000000  0.000000
 Maryland             0.005076   0.000000  0.000000
 Massachusetts        0.001015   0.001952  0.000000
 Michigan             0.003046   0.015966  0.000000
 Minnesota            0.017259   0.092402  0.000000
 Mississippi          0.000000   0.002113  0.000000
 Missouri             0.000000   0.020861  0.029851
 Montana              0.000000   0.000053  0.000000
 Nebraska             0.000000   0.023000  0.007024
 Nevada               0.000000   0.000000  0.011414
 New Hampshire        0.000000   0.000107  0.000000
 New Jersey           0.000000   0.005188  0.000000
 New Mexico           0.000000   0.006445  0.000000
 New York             0.000000   0.006740  0.000000
 North Carolina       0.028426   0.002033  0.000000
 North Dakota         0.000000   0.005108  0.000878
 Ohio                 0.119797   0.037442  0.014925
 Oklahoma             0.000000   0.000588  0.000000
 Oregon               0.000000   0.000856  0.017559
 Pennsylvania         0.090355   0.008371  0.000000
 Rhode Island         0.000000   0.000000  0.000000
 South Carolina       0.000000   0.000508  0.000000
 South Dakota         0.000000   0.013586  0.000000
 Tennessee            0.053807   0.004841  0.001756
 Texas                0.000000   0.009655  0.136962
 Utah                 0.000000   0.007970  0.079017
 Vermont              0.000000   0.002808  0.000000
 Virginia             0.138071   0.004092  0.000000
 Washington           0.000000   0.002541  0.008780
 West Virginia        0.441624   0.000027  0.000000
 Wisconsin            0.000000   0.504399  0.000000
 Wyoming              0.000000   0.000000  0.250219

 [50 rows x 50 columns],
 np.float64(2.0): dest             Alabama  Alaska   Arizona  Arkansas  California  Colorado  \
 origin
 Alabama         0.263598     0.0  0.052885  0.014837    0.015345  0.000000
 Alaska          0.000000     0.9  0.000000  0.000000    0.000000  0.000000
 Arizona         0.001395     0.0  0.084135  0.000000    0.006461  0.026042
 Arkansas        0.008368     0.0  0.000000  0.041543    0.001481  0.002604
 California      0.071130     0.0  0.228365  0.047478    0.643963  0.192708
 Colorado        0.000000     0.0  0.002404  0.002967    0.001077  0.026042
 Connecticut     0.000000     0.0  0.000000  0.000000    0.004173  0.002604
 Delaware        0.000000     0.0  0.000000  0.000000    0.000000  0.000000
 Florida         0.004184     0.0  0.009615  0.014837    0.002288  0.000000
 Georgia         0.025105     0.0  0.144231  0.133531    0.048593  0.341146
 Hawaii          0.000000     0.0  0.000000  0.000000    0.000269  0.000000
 Idaho           0.000000     0.0  0.004808  0.000000    0.000673  0.002604
 Illinois        0.043236     0.0  0.024038  0.000000    0.002692  0.015625
 Indiana         0.004184     0.0  0.000000  0.000000    0.001346  0.002604
 Iowa            0.001395     0.0  0.000000  0.000000    0.000404  0.002604
 Kansas          0.000000     0.0  0.000000  0.000000    0.002019  0.007812
 Kentucky        0.009763     0.0  0.000000  0.000000    0.002154  0.010417
 Louisiana       0.001395     0.0  0.033654  0.000000    0.000808  0.000000
 Maine           0.000000     0.0  0.007212  0.000000    0.000808  0.002604
 Maryland        0.001395     0.0  0.000000  0.000000    0.001481  0.000000
 Massachusetts   0.059972     0.0  0.007212  0.000000    0.007942  0.005208
 Michigan        0.000000     0.0  0.000000  0.000000    0.001615  0.010417
 Minnesota       0.009763     0.0  0.002404  0.035608    0.005115  0.007812
 Mississippi     0.006974     0.0  0.057692  0.008902    0.000404  0.000000
 Missouri        0.002789     0.0  0.004808  0.008902    0.013192  0.000000
 Montana         0.000000     0.0  0.000000  0.000000    0.001211  0.005208
 Nebraska        0.000000     0.0  0.002404  0.000000    0.004173  0.005208
 Nevada          0.000000     0.1  0.000000  0.000000    0.004173  0.010417
 New Hampshire   0.000000     0.0  0.002404  0.000000    0.001885  0.000000
 New Jersey      0.012552     0.0  0.000000  0.002967    0.007673  0.023438
 New Mexico      0.000000     0.0  0.000000  0.000000    0.000135  0.000000
 New York        0.037657     0.0  0.021635  0.000000    0.022749  0.005208
 North Carolina  0.301255     0.0  0.158654  0.465875    0.030287  0.046875
 North Dakota    0.000000     0.0  0.000000  0.000000    0.000000  0.000000
 Ohio            0.012552     0.0  0.002404  0.002967    0.003365  0.007812
 Oklahoma        0.004184     0.0  0.009615  0.011869    0.002558  0.015625
 Oregon          0.002789     0.0  0.004808  0.000000    0.004711  0.010417
 Pennsylvania    0.009763     0.0  0.024038  0.008902    0.012788  0.049479
 Rhode Island    0.000000     0.0  0.000000  0.000000    0.000000  0.000000
 South Carolina  0.041841     0.0  0.007212  0.002967    0.039844  0.018229
 South Dakota    0.000000     0.0  0.000000  0.000000    0.000135  0.000000
 Tennessee       0.051604     0.0  0.002404  0.053412    0.010634  0.015625
 Texas           0.006974     0.0  0.088942  0.044510    0.051689  0.080729
 Utah            0.000000     0.0  0.004808  0.014837    0.003769  0.007812
 Vermont         0.001395     0.0  0.000000  0.005935    0.000673  0.005208
 Virginia        0.001395     0.0  0.000000  0.056380    0.012249  0.000000
 Washington      0.000000     0.0  0.004808  0.000000    0.011172  0.013021
 West Virginia   0.000000     0.0  0.000000  0.000000    0.000000  0.000000
 Wisconsin       0.001395     0.0  0.002404  0.020772    0.009826  0.020833
 Wyoming         0.000000     0.0  0.000000  0.000000    0.000000  0.000000

 dest            Connecticut  Delaware   Florida   Georgia  ...  South Dakota  \
 origin                                                     ...
 Alabama            0.000000  0.038911  0.016514  0.038850  ...      0.000000
 Alaska             0.000000  0.000000  0.000000  0.000000  ...      0.000000
 Arizona            0.000000  0.000000  0.000000  0.000874  ...      0.000000
 Arkansas           0.000000  0.000000  0.000000  0.000971  ...      0.000000
 California         0.073770  0.000000  0.081040  0.003982  ...      0.227273
 Colorado           0.000000  0.000000  0.007645  0.000000  ...      0.000000
 Connecticut        0.422131  0.000000  0.007645  0.000000  ...      0.000000
 Delaware           0.000000  0.038911  0.000000  0.000000  ...      0.000000
 Florida            0.008197  0.031128  0.095107  0.000777  ...      0.000000
 Georgia            0.077869  0.003891  0.056881  0.779332  ...      0.000000
 Hawaii             0.000000  0.000000  0.000000  0.000000  ...      0.000000
 Idaho              0.000000  0.000000  0.000612  0.000097  ...      0.000000
 Illinois           0.000000  0.023346  0.048930  0.006119  ...      0.000000
 Indiana            0.004098  0.000000  0.004281  0.000097  ...      0.000000
 Iowa               0.000000  0.000000  0.001835  0.000000  ...      0.000000

In [386]:
df_shares

     CDP order           dest     val  sector_total     share
0          1.0        Alabama   11678       1072121  0.010892
1          1.0         Alaska    2131       1072121  0.001988
2          1.0        Arizona   18048       1072121  0.016834
3          1.0       Arkansas   16980       1072121  0.015838
4          1.0     California  131247       1072121  0.122418
..         ...            ...     ...           ...       ...
645       13.0       Virginia  367153      19524993  0.018804
646       13.0     Washington  438802      19524993  0.022474
647       13.0  West Virginia   84954      19524993  0.004351
648       13.0      Wisconsin  371530      19524993  0.019028
649       13.0        Wyoming   31546      19524993  0.001616

[650 rows x 5 columns]

In [387]:
domestic_expenditure

    ExportingIndustry         Value
0                 1.0  3.702758e+05
1                 2.0  5.021600e+04
2                 3.0  2.875896e+05
3                 4.0  3.924727e+05
4                 5.0  3.776814e+05
5                 6.0  1.617610e+05
6                 7.0  9.119060e+04
7                 8.0  5.297387e+05
8                 9.0  1.214166e+05
9                10.0  2.010416e+05
10               11.0  2.779642e+05
11               12.0  8.313151e+04
12               13.0  8.805743e+05
13               14.0  2.239603e+05
14               15.0  6.046541e+05
15               16.0  8.396479e+05
16               17.0  1.158419e+06
17               18.0  8.392791e+05
18               19.0  4.512257e+04
19               20.0  6.107469e+04
20               21.0  1.982918e+05
21               22.0  2.857253e+06

# Get grand expenditure share (CFS)

In [388]:
df_sum_by_dest = cfs_2017_collapsed.groupby('dest')['val'].sum()

# 2. Compute the grand total of 'val'.
grand_total = cfs_2017_collapsed['val'].sum()

# 3. Divide each state's total by the grand total to get the share.
grand_expenditure_shares = df_sum_by_dest / grand_total

In [389]:
grand_expenditure_shares.sort_values(ascending=False)

dest
Texas             0.132063
California        0.113394
Illinois          0.051990
New York          0.050691
Florida           0.048189
Ohio              0.040973
Pennsylvania      0.036634
Michigan          0.035739
Georgia           0.033333
New Jersey        0.028266
Indiana           0.027043
North Carolina    0.025998
Washington        0.024571
Tennessee         0.023789
Louisiana         0.020626
Wisconsin         0.020561
Virginia          0.020080
Minnesota         0.018228
Massachusetts     0.017571
Missouri          0.016816
Kentucky          0.015911
Alabama           0.014816
South Carolina    0.014371
Arizona           0.013864
Colorado          0.012609
Maryland          0.011918
Iowa              0.011628
Kansas            0.011547
Oklahoma          0.010791
Connecticut       0.010598
Oregon            0.010468
Mississippi       0.008752
Utah              0.007802
Arkansas          0.007513
Nebraska          0.006926
Nevada            0.005758
New Hampshire     0.003984
West Virginia     0.003930
Idaho             0.003736
North Dakota      0.003719
Montana           0.003227
New Mexico        0.003173
Maine             0.003043
South Dakota      0.002620
Delaware          0.002323
Hawaii            0.002296
Alaska            0.001684
Wyoming           0.001566
Rhode Island      0.001477
Vermont           0.001391
Name: val, dtype: float64

In [390]:
grand_expenditure_shares.sum()

np.float64(1.0)

# Get each state's share of [that sector's expenditure]

In [391]:
cfs_2017_collapsed.columns

Index(['dest', 'origin', 'CDP order', 'val'], dtype='object')

In [392]:
import pandas as pd

# Suppose your DataFrame is called df and has columns:
#   ['dest_abbrv', 'origin_abbrv', 'CDP order', 'val']

# 1) Sum over all origins to get total spending by (CDP order, dest_abbrv).
df_sum = cfs_2017_collapsed.groupby(['CDP order', 'dest'], as_index=False)['val'].sum()

# 2) Compute total expenditures by each sector (CDP order).
df_total = df_sum.groupby('CDP order', as_index=False)['val'].sum()
df_total = df_total.rename(columns={'val': 'sector_total'})

# 3) Merge back to compute shares
df_shares = pd.merge(df_sum, df_total, on='CDP order', how='left')
df_shares['share'] = df_shares['val'] / df_shares['sector_total']

# df_shares now has columns:
#   ['CDP order', 'dest_abbrv', 'val', 'sector_total', 'share']
# where share is the fraction of sector expenditure going to each state.

In [393]:
df_shares

     CDP order           dest     val  sector_total     share
0          1.0        Alabama   11678       1072121  0.010892
1          1.0         Alaska    2131       1072121  0.001988
2          1.0        Arizona   18048       1072121  0.016834
3          1.0       Arkansas   16980       1072121  0.015838
4          1.0     California  131247       1072121  0.122418
..         ...            ...     ...           ...       ...
645       13.0       Virginia  367153      19524993  0.018804
646       13.0     Washington  438802      19524993  0.022474
647       13.0  West Virginia   84954      19524993  0.004351
648       13.0      Wisconsin  371530      19524993  0.019028
649       13.0        Wyoming   31546      19524993  0.001616

[650 rows x 5 columns]

In [394]:
import pandas as pd

# trade_share_matrices[sector] = 50×50 DataFrame of shares
# domestic_expenditure has columns ['ExportingIndustry','Value']
# df_shares has columns ['CDP order','dest_abrv','shares']

scaled_trade_flows = {}  # to store the final dollar‐value trade flow matrices

# Get the list of unique sectors from the trade_share_matrices keys
all_sectors = list(trade_share_matrices.keys())

for sector in all_sectors:
    # 1. Retrieve the 50×50 “trade shares” matrix for this sector
    share_matrix = trade_share_matrices[sector].copy()
    
    # 2. Find the total U.S. expenditure for this sector
    #    (matching sector to ExportingIndustry in domestic_expenditure)
    sector_value = domestic_expenditure.loc[
        domestic_expenditure['ExportingIndustry'] == sector,
        'Value'
    ].values[0]
    
    # 3. Get the share of that total going to each destination state
    #    from df_shares (matching sector to CDP order)
    sector_shares_df = df_shares[df_shares['CDP order'] == sector]
    # Make it a Series indexed by destination state
    sector_shares_by_state = sector_shares_df.set_index('dest')['share']
    
    # Ensure it matches the columns in the share_matrix (50 states)
    sector_shares_by_state = sector_shares_by_state.reindex(
        share_matrix.columns,
        fill_value=0
    )
    
    # 4. Create the column‐by‐column scaling factor:
    #    "sector_value * sector_shares_by_state"
    #    (this is a Series whose index = states, same as share_matrix.columns)
    scale_by_state = sector_shares_by_state * sector_value
    
    # 5. Multiply each column of the 50×50 matrix by the column’s scale factor
    scaled_matrix = share_matrix.mul(scale_by_state, axis=1)
    
    # 6. Store the resulting (dollar‐valued) 50×50 matrix in a dictionary
    scaled_trade_flows[sector] = np.array(scaled_matrix)

# After this loop, scaled_trade_flows[sector] is the 50×50 matrix
# of trade flows in dollars for that sector, where each column has been
# scaled by [sector_value * share for that (sector,dest_state)].

# scaled_trade_flows is between-state, sectors 1-13

# Check totals.

In [395]:
sums_dict = {}
for key, matrix in scaled_trade_flows.items():
        # Calculate the sum of all elements in the matrix
        matrix_sum = matrix.sum()
        sums_dict[key] = matrix_sum

In [396]:
sums_dict

{np.float64(1.0): np.float64(370275.8303016197),
 np.float64(2.0): np.float64(50215.998282914414),
 np.float64(3.0): np.float64(287589.56145522813),
 np.float64(4.0): np.float64(392472.7117530798),
 np.float64(5.0): np.float64(377681.35514771746),
 np.float64(6.0): np.float64(161761.02304897114),
 np.float64(7.0): np.float64(91190.6043977333),
 np.float64(8.0): np.float64(529738.6981184247),
 np.float64(9.0): np.float64(121416.63225651279),
 np.float64(10.0): np.float64(201041.62447004678),
 np.float64(11.0): np.float64(277964.2173746787),
 np.float64(12.0): np.float64(83131.51020187109),
 np.float64(13.0): np.float64(880574.2975308779)}

# Bilateral expenditure shares 
# across US states [no sectors?]

In [397]:
import pandas as pd
import numpy as np

# Example: assume your DataFrame is called cfs_2017_collapsed
df = cfs_2017_collapsed

# Step 1: (Optional) group if you have multiple rows per (origin, destination).
#         If each pair is already unique, you can skip this groupby.
df_agg = df.groupby(['origin', 'dest'], as_index=False)['val'].sum()

# Step 2: pivot so that rows=origins, columns=destinations
pivot_df = df_agg.pivot_table(
    index='origin',
    columns='dest',
    values='val',
    aggfunc='sum',      # 'sum' if not already unique
    fill_value=0
)

# Step 3: create shares so that each column sums to 1
# (i.e., share of each destination's total spending on each origin)
pivot_shares = pivot_df.div(pivot_df.sum(axis=0), axis=1)

# Step 4: convert to a 2D NumPy array
result_matrix = pivot_shares.to_numpy()

print(result_matrix)

[[4.85346909e-01 5.87613116e-05 4.21697929e-03 ... 3.50070098e-03
  4.19770282e-03 9.05739863e-04]
 [0.00000000e+00 6.18893720e-01 1.66584961e-05 ... 0.00000000e+00
  3.20925292e-06 0.00000000e+00]
 [2.47855482e-03 7.63897050e-04 4.86375730e-01 ... 9.23446302e-05
  2.12452543e-03 5.28699315e-03]
 ...
 [3.60760001e-04 1.95871039e-05 3.52208203e-04 ... 3.79704329e-01
  7.52569809e-04 2.94892048e-04]
 [7.00141632e-03 1.44944568e-03 7.36067548e-03 ... 6.49770398e-03
  4.44407716e-01 3.60189573e-03]
 [1.78153087e-05 1.95871039e-05 3.47448632e-04 ... 8.39496638e-06
  1.42811755e-04 4.39957873e-01]]

In [398]:
result_matrix
column_sums = result_matrix.sum(axis=0)
print(column_sums)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]

In [399]:
pivot_df

dest,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,Florida,Georgia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
origin,,,,,,,,,,,,,,,,,,,,,
Alabama,217946,3,1772,1903,14537,1136,378,451,31855,44899,...,95,28013,22250,764,19,3011,1332,417,2616,43
Alaska,0,31597,7,0,128,0,0,0,10,0,...,0,0,40,0,2,4,3685,0,2,0
Arizona,1113,39,204378,209,52855,2963,1337,33,5338,1222,...,82,1840,21866,2375,7,2085,3612,11,1324,251
Arkansas,2350,1,1544,99863,6723,806,205,31,2887,4581,...,94,8759,20410,977,1,845,972,68,1644,96
California,19160,1670,80930,5794,2498320,27289,12412,1864,86820,37250,...,1221,28676,160856,34744,788,27062,71057,1880,18527,1534
Colorado,793,89,3344,254,22062,224871,476,39,4250,1814,...,1762,1768,14396,12120,0,1108,2993,51,1729,9799
Connecticut,714,39,1250,138,10151,894,164939,195,6907,2996,...,23,11996,7655,610,2032,2434,1035,104,1685,18
Delaware,104,0,1809,95,2846,418,699,31710,462,655,...,6,1247,1791,73,52,1095,341,17,417,5
Florida,15227,25,3776,1537,24070,2091,3495,681,824388,37943,...,201,8685,26301,772,168,10344,6020,537,4024,126
Georgia,40203,300,3803,4563,28468,3001,2220,738,73988,461754,...,70,50495,44725,2331,27,11136,5776,1367,9940,39
Hawaii,1,2,16,0,449,10,0,2,38,4,...,0,7,11,4,2,10,6,0,2,0
Idaho,95,715,854,27,7388,1671,35,0,867,864,...,43,471,2989,5549,0,221,6490,9,358,706
Illinois,9299,127,7202,6407,54960,10040,2804,466,29516,20393,...,2505,19894,60609,4074,747,20306,10052,1129,112926,231
Indiana,7979,16,3515,2832,24161,3062,1811,202,18867,15897,...,522,16373,38035,1228,295,6792,4071,1411,15520,257
Iowa,1848,47,3251,2056,11026,3698,539,171,6233,7629,...,5230,2985,18852,1237,172,5512,3672,212,13819,478
Kansas,1033,813,2130,2105,13484,6514,517,3,6146,6633,...,809,4586,24923,824,3,1569,830,114,3245,345
Kentucky,7296,5,1953,1606,13360,1618,1368,102,11494,11028,...,196,32137,26879,802,155,6677,2457,9314,4594,3
Louisiana,6716,27,1151,3743,7935,609,36,75,11362,11039,...,49,2223,71646,393,20,2798,640,845,1166,143
Maine,117,0,220,16,938,87,843,15,542,506,...,19,699,562,159,633,514,84,7,636,0
Maryland,1025,22,905,122,11356,465,1703,5980,6446,1479,...,5,1479,6962,815,100,46986,167,1423,443,8
Massachusetts,2105,67,3103,182,22241,2094,32404,136,11621,5630,...,129,5342,19651,900,6805,4500,2511,491,2375,7
Michigan,7942,204,6832,2804,40211,3551,2620,910,14912,11815,...,524,27418,62597,2929,384,5607,5587,1018,17873,200
Minnesota,2120,116,3391,1201,25279,3264,1244,103,12818,4467,...,10476,4419,18117,2006,221,2580,13268,514,44418,324
Mississippi,9150,17,825,5660,12097,645,336,106,10868,5779,...,125,8748,13967,466,0,1509,1166,148,1254,79
Missouri,2371,30,3223,11945,24732,4151,446,172,7533,8124,...,1226,8259,30301,682,299,6353,3989,671,5086,246
Montana,1,5,186,46,1157,424,6,0,101,35,...,374,160,566,561,1,55,5288,95,266,1541
Nebraska,396,9,1033,1439,10990,3527,149,49,3424,1728,...,4402,1900,12329,976,3,551,1513,29,2681,788
Nevada,67,548,3201,103,19458,1048,100,0,1385,320,...,54,382,1811,2556,13,292,2828,20,95,201
New Hampshire,262,282,584,66,4580,342,2451,30,1738,794,...,8,716,4722,281,2497,640,443,54,566,14
New Jersey,3249,277,4747,3360,35171,2584,23159,9160,31203,14159,...,202,11366,28787,2588,627,19176,4377,2119,4441,38
New Mexico,235,0,916,15,3332,2109,4,0,385,93,...,0,1241,9302,340,0,98,101,0,632,0
New York,6491,910,5604,2450,57878,5144,20807,1871,32617,15559,...,464,10962,44751,2969,7307,12842,7592,1747,8447,36
North Carolina,7547,27,4368,4037,29327,3121,2451,1530,32737,39773,...,413,19334,32386,1830,432,47383,5016,2897,5826,102
North Dakota,2,13,72,98,1433,185,81,0,460,359,...,4107,259,1352,73,0,139,7470,0,746,45
Ohio,10024,283,4413,3687,32374,4641,4619,785,18095,19738,...,582,22192,43792,2662,368,16532,6680,12667,18273,270
Oklahoma,1136,23,1791,5917,8492,2535,69,52,2245,2347,...,137,3070,48692,453,51,739,2116,49,1255,621
Oregon,376,611,4435,118,32009,1744,76,33,2125,1635,...,189,10553,5667,2225,98,934,52983,93,949,205
Pennsylvania,4514,96,4915,2503,26101,5846,12712,7334,22735,14251,...,308,9863,31420,3554,1291,31662,5631,16971,8108,429
Rhode Island,573,40,482,300,2238,237,4789,24,2391,948,...,63,545,2967,271,1441,399,275,37,547,23
South Carolina,7336,0,1778,3149,10623,876,1376,524,14698,51952,...,79,11966,23209,930,12,8522,1237,1473,2432,13
South Dakota,239,1,228,239,1554,659,46,30,285,375,...,38472,755,3246,140,9,497,4756,13,1718,673
Tennessee,25948,132,3244,20024,22495,2567,1268,136,21867,78139,...,536,270944,44248,1402,183,16534,2577,3184,6986,46
Texas,15427,216,24257,20936,107755,24649,4175,871,51399,35092,...,1008,31743,2863241,15897,396,11037,12462,3364,9872,2801
Utah,948,146,4621,437,25307,5152,303,166,2293,2774,...,160,5898,11316,112264,18,569,4960,80,1414,2953
Vermont,131,2,66,10,1126,62,855,16,921,1777,...,5,814,1479,32,13911,388,425,49,358,11
Virginia,3298,8,1082,1089,10608,1386,1879,3146,9098,10174,...,25,6951,15124,1507,145,258492,1802,6278,2800,70
Washington,831,11378,3612,348,38142,3965,4911,108,10380,2862,...,254,13559,26855,3417,44,2004,457071,137,1651,585
West Virginia,162,1,148,140,1072,59,131,94,382,773,...,0,1020,2753,11,73,3076,155,45230,469,14
Wisconsin,3144,74,3093,2144,23117,3038,1936,277,11406,10221,...,1934,8307,25595,2386,295,5003,4942,774,276954,171
Wyoming,8,1,146,2,773,1311,5,2,29,29,...,213,1,722,309,0,0,219,1,89,20887

# CDP 2019 do not say what they do for services. 
# [tbh, might make sense to use the local employment thing here, too. may see if that changes results]

we will impute service trade using the following (knowing we need to match domestic aggregates)

note, all of this will only apply to ExportingIndustry [13,...,22]  in `domestic_expenditure` dataframe which has columns ExportingIndustry and Value (value is total domestic expenditure in that industry)

 (1) First we have total domestic expenditure shares by state. (what percent of domestic expenditure is spent by each state, using CFS.). this is called grand_expenditure_shares, which is a list, with the states in order, as the labels.

 (2) Then we allocate domestic service expenditure from WIOD, called, domestic_expenditure, this is just the 22 sectors dataframe from before

 (3) Then we assume the same aggregate trade shares for goods also applies to services, this is called [result_matrix],2d nparray columns of which are destinatino, rows of which are origin, again states are in same order. Each column sums to 1

 We use these to create a matrix for each sector. 

We want the ratio of the row values for each column to match that row in result_matrix (which are shares), basically. We want the sum total of the matrix to be equal to the sectoral total expenditure from domestic_expenditure. We want the sum of the column to be (grand_expenditure_share) * (domestic_expenditure for that sector)


 # So at the end of this, should have a 50 x 50 matrix for each of the 10 sectors under consideration
 
 (total expenditure in that sector from WIOD, scales the entire sector's matrix)
 (agg. [goods] expenditure share scales each column)
 (agg. [goods] trade shares give each column's dispersion )

In [400]:
first_missing_sector = 14 # I think we have 13 (retail trade)

In [401]:
import numpy as np
import pandas as pd

# Assume these are provided:
# domestic_expenditure: DataFrame with columns ['ExportingIndustry', 'Value']
# result_matrix: 50 x 50 numpy array (each column sums to 1)
# grand_expenditure_shares: numpy array of length 50 (sums to 1)

# Dictionary to hold the imputed matrices for each sector
sector_matrices = {}

# Filter the dataframe for the industries of interest (13 to 22)
sectors = domestic_expenditure[domestic_expenditure['ExportingIndustry'].isin(range(first_missing_sector, 23))]

for _, row in sectors.iterrows():
    sector = row['ExportingIndustry']
    sector_total = row['Value']
    
    # Initialize an empty 50x50 matrix for this sector
    imputed_matrix = np.zeros_like(result_matrix)
    
    # For each destination state (column index j)
    for j in range(result_matrix.shape[1]):
        # Compute allocated total for destination state j
        allocated_total = grand_expenditure_shares[j] * sector_total
        
        # Scale the goods trade shares for column j
        imputed_matrix[:, j] = result_matrix[:, j] * allocated_total
    
    # Store the matrix in the dictionary
    sector_matrices[sector] = imputed_matrix

# Now, sector_matrices holds a 50x50 imputed service trade matrix for each sector (13-22)

/var/folders/g9/ggrmf_5j6tx4rv5qdhs0slq40000gn/T/ipykernel_45649/3098510060.py:25: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  allocated_total = grand_expenditure_shares[j] * sector_total

In [402]:
sector_matrices

{np.float64(14.0): array([[1.61044663e+03, 2.21676006e-02, 1.30936628e+01, ...,
         3.08129649e+00, 1.93301478e+01, 3.17735609e-01],
        [0.00000000e+00, 2.33476559e+02, 5.17244015e-02, ...,
         0.00000000e+00, 1.47784004e-02, 0.00000000e+00],
        [8.22417984e+00, 2.88178808e-01, 1.51018996e+03, ...,
         8.12812023e-02, 9.78330108e+00, 1.85468925e+00],
        ...,
        [1.19705043e+00, 7.38920021e-03, 1.09360163e+00, ...,
         3.34213526e+02, 3.46553490e+00, 1.03448803e-01],
        [2.32316455e+01, 5.46800816e-01, 2.28547963e+01, ...,
         5.71924096e+00, 2.04646856e+03, 1.26355324e+00],
        [5.91136017e-02, 7.38920021e-03, 1.07882323e+00, ...,
         7.38920021e-03, 6.57638819e-01, 1.54338225e+02]], shape=(50, 50)),
 np.float64(15.0): array([[4.34792782e+03, 5.98486940e-02, 3.53506286e+01, ...,
         8.31896847e+00, 5.21880612e+01, 8.57831281e-01],
        [0.00000000e+00, 6.30346395e+02, 1.39646953e-01, ...,
         0.00000000e+00, 3.98991294e-02, 0.00000000e+00],
        [2.22038655e+01, 7.78033023e-01, 4.07725213e+03, ...,
         2.19445211e-01, 2.64132236e+01, 5.00734073e+00],
        ...,
        [3.23182948e+00, 1.99495647e-02, 2.95253557e+00, ...,
         9.02318810e+02, 9.35634583e+00, 2.79293906e-01],
        [6.27214314e+01, 1.47626779e+00, 6.17040036e+01, ...,
         1.54409631e+01, 5.52511174e+03, 3.41137556e+00],
        [1.59596517e-01, 1.99495647e-02, 2.91263644e+00, ...,
         1.99495647e-02, 1.77551126e+00, 4.16686557e+02]], shape=(50, 50)),
 np.float64(16.0): array([[6.03771448e+03, 8.31084004e-02, 4.90893619e+01, ...,
         1.15520677e+01, 7.24705252e+01, 1.19122041e+00],
        [0.00000000e+00, 8.75325376e+02, 1.93919601e-01, ...,
         0.00000000e+00, 5.54056003e-02, 0.00000000e+00],
        [3.08332166e+01, 1.08040921e+00, 5.66184289e+03, ...,
         3.04730802e-01, 3.66785074e+01, 6.95340284e+00],
        ...,
        [4.48785362e+00, 2.77028001e-02, 4.10001442e+00, ...,
         1.25299765e+03, 1.29926133e+01, 3.87839202e-01],
        [8.70976037e+01, 2.05000721e+00, 8.56847609e+01, ...,
         2.14419673e+01, 7.67240131e+03, 4.73717883e+00],
        [2.21622401e-01, 2.77028001e-02, 4.04460882e+00, ...,
         2.77028001e-02, 2.46554921e+00, 5.78628387e+02]], shape=(50, 50)),
 np.float64(17.0): array([[8.32992506e+03, 1.14660398e-01, 6.77260753e+01, ...,
         1.59377954e+01, 9.99838673e+01, 1.64346571e+00],
        [0.00000000e+00, 1.20764154e+03, 2.67540929e-01, ...,
         0.00000000e+00, 7.64402655e-02, 0.00000000e+00],
        [4.25390078e+01, 1.49058518e+00, 7.81135430e+03, ...,
         4.20421461e-01, 5.06034558e+01, 9.59325333e+00],
        ...,
        [6.19166151e+00, 3.82201328e-02, 5.65657965e+00, ...,
         1.72869661e+03, 1.79252423e+01, 5.35081859e-01],
        [1.20164097e+02, 2.82828983e+00, 1.18214871e+02, ...,
         2.95823828e+01, 1.05852187e+04, 6.53564270e+00],
        [3.05761062e-01, 3.82201328e-02, 5.58013938e+00, ...,
         3.82201328e-02, 3.40159182e+00, 7.98303913e+02]], shape=(50, 50)),
 np.float64(18.0): array([[6.03506225e+03, 8.30718929e-02, 4.90677981e+01, ...,
         1.15469931e+01, 7.24386906e+01, 1.19069713e+00],
        [0.00000000e+00, 8.74940866e+02, 1.93834417e-01, ...,
         0.00000000e+00, 5.53812619e-02, 0.00000000e+00],
        [3.08196723e+01, 1.07993461e+00, 5.65935577e+03, ...,
         3.04596941e-01, 3.66623954e+01, 6.95034837e+00],
        ...,
        [4.48588222e+00, 2.76906310e-02, 4.09821338e+00, ...,
         1.25244724e+03, 1.29869059e+01, 3.87668833e-01],
        [8.70593437e+01, 2.04910669e+00, 8.56471216e+01, ...,
         2.14325484e+01, 7.66903101e+03, 4.73509789e+00],
        [2.21525048e-01, 2.76906310e-02, 4.04283212e+00, ...,
         2.76906310e-02, 2.46446616e+00, 5.78374209e+02]], shape=(50, 50)),
 np.float64(19.0): array([[3.24466000e+02, 4.46623476e-03, 2.63805600e+00, ...,
         6.20806632e-01, 3.89455671e+00, 6.40160316e-02],
        [0.00000000e+00, 4.70398732e+01, 1.04212144e-02, ...,
         0.00000000e+00, 2.97748984e-03, 0.00000000e+00],
        [1.65697310e+00, 5.80610519e-02, 3.04266709e+02, ...,
         1.63761941e-02, 1.97109827e+00, 3.73674975e-01],
        ...,
        [2.41176677e-01, 1.48874492e-03, 2.20334248e-01, ...,
         6.73359327e+01, 6.98221367e-01, 2.08424289e-02],
        [4.68061403e+00, 1.10167124e-01, 4.60468804e+00, ...,
         1.15228857e+00, 4.12313861e+02, 2.54575381e-01],
        [1.19099594e-02, 1.48874492e-03, 2.17356758e-01, ...,
         1.48874492e-03, 1.32498298e-01, 3.10954151e+01]], shape=(50, 50)),
 np.float64(20.0): array([[4.39174025e+02, 6.04517667e-03, 3.57068436e+00, ...,
         8.40279558e-01, 5.27139406e+00, 8.66475323e-02],
        [0.00000000e+00, 6.36698158e+01, 1.41054122e-02, ...,
         0.00000000e+00, 4.03011778e-03, 0.00000000e+00],
        [2.24276055e+00, 7.85872968e-02, 4.11833706e+02, ...,
         2.21656478e-02, 2.66793797e+00, 5.05779782e-01],
        ...,
        [3.26439540e-01, 2.01505889e-03, 2.98228716e-01, ...,
         9.11411137e+01, 9.45062620e-01, 2.82108245e-02],
        [6.33534515e+00, 1.49114358e-01, 6.23257715e+00, ...,
         1.55965558e+00, 5.58078620e+02, 3.44575070e-01],
        [1.61204711e-02, 2.01505889e-03, 2.94198598e-01, ...,
         2.01505889e-03, 1.79340241e-01, 4.20885351e+01]], shape=(50, 50)),
 np.float64(21.0): array([[1.42587045e+03, 1.96269321e-02, 1.15929746e+01, ...,
         2.72814357e+00, 1.71146848e+01, 2.81319361e-01],
        [0.00000000e+00, 2.06717392e+02, 4.57961750e-02, ...,
         0.00000000e+00, 1.30846214e-02, 0.00000000e+00],
        [7.28159183e+00, 2.55150118e-01, 1.33710438e+03, ...,
         7.19654179e-02, 8.66201939e+00, 1.64211999e+00],
        ...,
        [1.05985434e+00, 6.54231072e-03, 9.68261986e-01, ...,
         2.95908714e+02, 3.06834373e+00, 9.15923500e-02],
        [2.05690249e+01, 4.84130993e-01, 2.02353670e+01, ...,
         5.06374849e+00, 1.81191912e+03, 1.11873513e+00],
        [5.23384857e-02, 6.54231072e-03, 9.55177365e-01, ...,
         6.54231072e-03, 5.82265654e-01, 1.36649244e+02]], shape=(50, 50)),
 np.float64(22.0): array([[2.05458476e+04, 2.82811076e-01, 1.67047076e+02, ...,
         3.93107396e+01, 2.46611258e+02, 4.05362543e+00],
        [0.00000000e+00, 2.97866053e+03, 6.59892511e-01, ...,
         0.00000000e+00, 1.88540717e-01, 0.00000000e+00],
        [1.04922909e+02, 3.67654399e+00, 1.92667874e+04, ...,
         1.03697395e+00, 1.24813955e+02, 2.36618600e+01],
        ...,
        [1.52717981e+01, 9.42703587e-02, 1.39520131e+01, ...,
         4.26384833e+03, 4.42127983e+01, 1.31978502e+00],
        [2.96386008e+02, 6.97600655e+00, 2.91578220e+02, ...,
         7.29652577e+01, 2.61085529e+04, 1.61202313e+01],
        [7.54162870e-01, 9.42703587e-02, 1.37634724e+01, ...,
         9.42703587e-02, 8.39006193e+00, 1.96902498e+03]], shape=(50, 50))}

In [403]:
grand_expenditure_shares.values

array([0.01481573, 0.00168444, 0.013864  , 0.00751321, 0.11339449,
       0.01260871, 0.01059829, 0.00232349, 0.048189  , 0.03333345,
       0.00229637, 0.00373594, 0.05199033, 0.02704284, 0.01162791,
       0.01154655, 0.01591144, 0.02062573, 0.00304284, 0.01191783,
       0.01757134, 0.0357388 , 0.0182279 , 0.00875248, 0.01681641,
       0.00322738, 0.00692626, 0.00575783, 0.00398448, 0.0282656 ,
       0.00317333, 0.05069118, 0.02599761, 0.00371927, 0.04097326,
       0.01079054, 0.01046826, 0.0366341 , 0.00147691, 0.01437062,
       0.00261971, 0.02378887, 0.13206325, 0.00780187, 0.00139057,
       0.02008048, 0.02457121, 0.00393014, 0.02056139, 0.00156636])

In [404]:
import numpy as np

# Set tolerance for numerical comparisons
tol = 1e-8

# Loop through each imputed sector matrix (for sectors 13-22)
for sector, imputed_matrix in sector_matrices.items():
    # Retrieve the sector total from domestic_expenditure dataframe
    sector_total = domestic_expenditure.loc[
        domestic_expenditure['ExportingIndustry'] == sector, 'Value'
    ].values[0]
    
    print(f"\nChecking Sector {sector}:")
    
    # --- Overall Sum Check ---
    total_sum = imputed_matrix.sum()
    if np.allclose(total_sum, sector_total, atol=tol):
        print("  Overall sum check passed.")
    else:
        print(f"  Overall sum check failed: Sum = {total_sum}, Expected = {sector_total}")
    
    # --- Column Sums Check ---
    column_sums = imputed_matrix.sum(axis=0)
    expected_column_sums = grand_expenditure_shares * sector_total
    if np.allclose(column_sums, expected_column_sums, atol=tol):
        print("  Column sums check passed.")
    else:
        # Report differences for each column if they don't match
        for j in range(len(column_sums)):
            if not np.allclose(column_sums[j], expected_column_sums[j], atol=tol):
                print(f"  Column {j} sum check failed: Sum = {column_sums[j]}, Expected = {expected_column_sums[j]}")
    
    # --- Row Ratios Check for Each Column ---
    for j in range(imputed_matrix.shape[1]):
        allocated_total = expected_column_sums[j]
        # Only check ratios if allocated_total is greater than tolerance
        if allocated_total > tol:
            ratios = imputed_matrix[:, j] / allocated_total
            if np.allclose(ratios, result_matrix[:, j], atol=tol):
                print(f"  Column {j} row ratios check passed.")
            else:
                print(f"  Column {j} row ratios check failed.")
        else:
            # If allocated_total is nearly zero, expect the entire column to be zeros
            if np.allclose(imputed_matrix[:, j], 0, atol=tol):
                print(f"  Column {j} is all zeros as expected (allocated total is zero).")
            else:
                print(f"  Column {j} expected to be zero but is not (check failed).")

Checking Sector 14.0:
  Overall sum check passed.
  Column sums check passed.
  Column 0 row ratios check passed.
  Column 1 row ratios check passed.
  Column 2 row ratios check passed.
  Column 3 row ratios check passed.
  Column 4 row ratios check passed.
  Column 5 row ratios check passed.
  Column 6 row ratios check passed.
  Column 7 row ratios check passed.
  Column 8 row ratios check passed.
  Column 9 row ratios check passed.
  Column 10 row ratios check passed.
  Column 11 row ratios check passed.
  Column 12 row ratios check passed.
  Column 13 row ratios check passed.
  Column 14 row ratios check passed.
  Column 15 row ratios check passed.
  Column 16 row ratios check passed.
  Column 17 row ratios check passed.
  Column 18 row ratios check passed.
  Column 19 row ratios check passed.
  Column 20 row ratios check passed.
  Column 21 row ratios check passed.
  Column 22 row ratios check passed.
  Column 23 row ratios check passed.
  Column 24 row ratios check passed.
  Column 25 row ratios check passed.
  Column 26 row ratios check passed.
  Column 27 row ratios check passed.
  Column 28 row ratios check passed.
  Column 29 row ratios check passed.
  Column 30 row ratios check passed.
  Column 31 row ratios check passed.
  Column 32 row ratios check passed.
  Column 33 row ratios check passed.
  Column 34 row ratios check passed.
  Column 35 row ratios check passed.
  Column 36 row ratios check passed.
  Column 37 row ratios check passed.
  Column 38 row ratios check passed.
  Column 39 row ratios check passed.
  Column 40 row ratios check passed.
  Column 41 row ratios check passed.
  Column 42 row ratios check passed.
  Column 43 row ratios check passed.
  Column 44 row ratios check passed.
  Column 45 row ratios check passed.
  Column 46 row ratios check passed.
  Column 47 row ratios check passed.
  Column 48 row ratios check passed.
  Column 49 row ratios check passed.

Checking Sector 15.0:
  Overall sum check passed.
  Column sums check passed.
  Column 0 row ratios check passed.
  Column 1 row ratios check passed.
  Column 2 row ratios check passed.
  Column 3 row ratios check passed.
  Column 4 row ratios check passed.
  Column 5 row ratios check passed.
  Column 6 row ratios check passed.
  Column 7 row ratios check passed.
  Column 8 row ratios check passed.
  Column 9 row ratios check passed.
  Column 10 row ratios check passed.
  Column 11 row ratios check passed.
  Column 12 row ratios check passed.
  Column 13 row ratios check passed.
  Column 14 row ratios check passed.
  Column 15 row ratios check passed.
  Column 16 row ratios check passed.
  Column 17 row ratios check passed.
  Column 18 row ratios check passed.
  Column 19 row ratios check passed.
  Column 20 row ratios check passed.
  Column 21 row ratios check passed.
  Column 22 row ratios check passed.
  Column 23 row ratios check passed.
  Column 24 row ratios check passed.
  Column 25 row ratios check passed.
  Column 26 row ratios check passed.
  Column 27 row ratios check passed.
  Column 28 row ratios check passed.
  Column 29 row ratios check passed.
  Column 30 row ratios check passed.
  Column 31 row ratios check passed.
  Column 32 row ratios check passed.
  Column 33 row ratios check passed.
  Column 34 row ratios check passed.
  Column 35 row ratios check passed.
  Column 36 row ratios check passed.
  Column 37 row ratios check passed.
  Column 38 row ratios check passed.
  Column 39 row ratios check passed.
  Column 40 row ratios check passed.
  Column 41 row ratios check passed.
  Column 42 row ratios check passed.
  Column 43 row ratios check passed.
  Column 44 row ratios check passed.
  Column 45 row ratios check passed.
  Column 46 row ratios check passed.
  Column 47 row ratios check passed.
  Column 48 row ratios check passed.
  Column 49 row ratios check passed.

Checking Sector 16.0:
  Overall sum check passed.
  Column sums check passed.
  Column 0 row ratios check passed.
  Column 1 row ratios check passed.
  Column 2 row ratios check passed.
  Column 3 row ratios check passed.
  Column 4 row ratios check passed.
  Column 5 row ratios check passed.
  Column 6 row ratios check passed.
  Column 7 row ratios check passed.
  Column 8 row ratios check passed.
  Column 9 row ratios check passed.
  Column 10 row ratios check passed.
  Column 11 row ratios check passed.
  Column 12 row ratios check passed.
  Column 13 row ratios check passed.
  Column 14 row ratios check passed.
  Column 15 row ratios check passed.
  Column 16 row ratios check passed.
  Column 17 row ratios check passed.
  Column 18 row ratios check passed.
  Column 19 row ratios check passed.
  Column 20 row ratios check passed.
  Column 21 row ratios check passed.
  Column 22 row ratios check passed.
  Column 23 row ratios check passed.
  Column 24 row ratios check passed.
  Column 25 row ratios check passed.
  Column 26 row ratios check passed.
  Column 27 row ratios check passed.
  Column 28 row ratios check passed.
  Column 29 row ratios check passed.
  Column 30 row ratios check passed.
  Column 31 row ratios check passed.
  Column 32 row ratios check passed.
  Column 33 row ratios check passed.
  Column 34 row ratios check passed.
  Column 35 row ratios check passed.
  Column 36 row ratios check passed.
  Column 37 row ratios check passed.
  Column 38 row ratios check passed.
  Column 39 row ratios check passed.
  Column 40 row ratios check passed.
  Column 41 row ratios check passed.
  Column 42 row ratios check passed.
  Column 43 row ratios check passed.
  Column 44 row ratios check passed.
  Column 45 row ratios check passed.
  Column 46 row ratios check passed.
  Column 47 row ratios check passed.
  Column 48 row ratios check passed.
  Column 49 row ratios check passed.

Checking Sector 17.0:
  Overall sum check passed.
  Column sums check passed.
  Column 0 row ratios check passed.
  Column 1 row ratios check passed.
  Column 2 row ratios check passed.
  Column 3 row ratios check passed.
  Column 4 row ratios check passed.
  Column 5 row ratios check passed.
  Column 6 row ratios check passed.
  Column 7 row ratios check passed.
  Column 8 row ratios check passed.
  Column 9 row ratios check passed.
  Column 10 row ratios check passed.
  Column 11 row ratios check passed.
  Column 12 row ratios check passed.
  Column 13 row ratios check passed.
  Column 14 row ratios check passed.
  Column 15 row ratios check passed.
  Column 16 row ratios check passed.
  Column 17 row ratios check passed.
  Column 18 row ratios check passed.
  Column 19 row ratios check passed.
  Column 20 row ratios check passed.
  Column 21 row ratios check passed.
  Column 22 row ratios check passed.
  Column 23 row ratios check passed.
  Column 24 row ratios check passed.
  Column 25 row ratios check passed.
  Column 26 row ratios check passed.
  Column 27 row ratios check passed.
  Column 28 row ratios check passed.
  Column 29 row ratios check passed.
  Column 30 row ratios check passed.
  Column 31 row ratios check passed.
  Column 32 row ratios check passed.
  Column 33 row ratios check passed.
  Column 34 row ratios check passed.
  Column 35 row ratios check passed.
  Column 36 row ratios check passed.
  Column 37 row ratios check passed.
  Column 38 row ratios check passed.
  Column 39 row ratios check passed.
  Column 40 row ratios check passed.
  Column 41 row ratios check passed.
  Column 42 row ratios check passed.
  Column 43 row ratios check passed.
  Column 44 row ratios check passed.
  Column 45 row ratios check passed.
  Column 46 row ratios check passed.
  Column 47 row ratios check passed.
  Column 48 row ratios check passed.
  Column 49 row ratios check passed.

Checking Sector 18.0:
  Overall sum check passed.
  Column sums check passed.
  Column 0 row ratios check passed.
  Column 1 row ratios check passed.
  Column 2 row ratios check passed.
  Column 3 row ratios check passed.
  Column 4 row ratios check passed.
  Column 5 row ratios check passed.
  Column 6 row ratios check passed.
  Column 7 row ratios check passed.
  Column 8 row ratios check passed.
  Column 9 row ratios check passed.
  Column 10 row ratios check passed.
  Column 11 row ratios check passed.
  Column 12 row ratios check passed.
  Column 13 row ratios check passed.
  Column 14 row ratios check passed.
  Column 15 row ratios check passed.
  Column 16 row ratios check passed.
  Column 17 row ratios check passed.
  Column 18 row ratios check passed.
  Column 19 row ratios check passed.
  Column 20 row ratios check passed.
  Column 21 row ratios check passed.
  Column 22 row ratios check passed.
  Column 23 row ratios check passed.
  Column 24 row ratios check passed.
  Column 25 row ratios check passed.
  Column 26 row ratios check passed.
  Column 27 row ratios check passed.
  Column 28 row ratios check passed.
  Column 29 row ratios check passed.
  Column 30 row ratios check passed.
  Column 31 row ratios check passed.
  Column 32 row ratios check passed.
  Column 33 row ratios check passed.
  Column 34 row ratios check passed.
  Column 35 row ratios check passed.
  Column 36 row ratios check passed.
  Column 37 row ratios check passed.
  Column 38 row ratios check passed.
  Column 39 row ratios check passed.
  Column 40 row ratios check passed.
  Column 41 row ratios check passed.
  Column 42 row ratios check passed.
  Column 43 row ratios check passed.
  Column 44 row ratios check passed.
  Column 45 row ratios check passed.
  Column 46 row ratios check passed.
  Column 47 row ratios check passed.
  Column 48 row ratios check passed.
  Column 49 row ratios check passed.

Checking Sector 19.0:
  Overall sum check passed.
  Column sums check passed.
  Column 0 row ratios check passed.
  Column 1 row ratios check passed.
  Column 2 row ratios check passed.
  Column 3 row ratios check passed.
  Column 4 row ratios check passed.
  Column 5 row ratios check passed.
  Column 6 row ratios check passed.
  Column 7 row ratios check passed.
  Column 8 row ratios check passed.
  Column 9 row ratios check passed.
  Column 10 row ratios check passed.
  Column 11 row ratios check passed.
  Column 12 row ratios check passed.
  Column 13 row ratios check passed.
  Column 14 row ratios check passed.
  Column 15 row ratios check passed.
  Column 16 row ratios check passed.
  Column 17 row ratios check passed.
  Column 18 row ratios check passed.
  Column 19 row ratios check passed.
  Column 20 row ratios check passed.
  Column 21 row ratios check passed.
  Column 22 row ratios check passed.
  Column 23 row ratios check passed.
  Column 24 row ratios check passed.
  Column 25 row ratios check passed.
  Column 26 row ratios check passed.
  Column 27 row ratios check passed.
  Column 28 row ratios check passed.
  Column 29 row ratios check passed.
  Column 30 row ratios check passed.
  Column 31 row ratios check passed.
  Column 32 row ratios check passed.
  Column 33 row ratios check passed.
  Column 34 row ratios check passed.
  Column 35 row ratios check passed.
  Column 36 row ratios check passed.
  Column 37 row ratios check passed.
  Column 38 row ratios check passed.
  Column 39 row ratios check passed.
  Column 40 row ratios check passed.
  Column 41 row ratios check passed.
  Column 42 row ratios check passed.
  Column 43 row ratios check passed.
  Column 44 row ratios check passed.
  Column 45 row ratios check passed.
  Column 46 row ratios check passed.
  Column 47 row ratios check passed.
  Column 48 row ratios check passed.
  Column 49 row ratios check passed.

Checking Sector 20.0:
  Overall sum check passed.
  Column sums check passed.
  Column 0 row ratios check passed.
  Column 1 row ratios check passed.
  Column 2 row ratios check passed.
  Column 3 row ratios check passed.
  Column 4 row ratios check passed.
  Column 5 row ratios check passed.
  Column 6 row ratios check passed.
  Column 7 row ratios check passed.
  Column 8 row ratios check passed.
  Column 9 row ratios check passed.
  Column 10 row ratios check passed.
  Column 11 row ratios check passed.
  Column 12 row ratios check passed.
  Column 13 row ratios check passed.
  Column 14 row ratios check passed.
  Column 15 row ratios check passed.
  Column 16 row ratios check passed.
  Column 17 row ratios check passed.
  Column 18 row ratios check passed.
  Column 19 row ratios check passed.
  Column 20 row ratios check passed.
  Column 21 row ratios check passed.
  Column 22 row ratios check passed.
  Column 23 row ratios check passed.
  Column 24 row ratios check passed.
  Column 25 row ratios check passed.
  Column 26 row ratios check passed.
  Column 27 row ratios check passed.
  Column 28 row ratios check passed.
  Column 29 row ratios check passed.
  Column 30 row ratios check passed.
  Column 31 row ratios check passed.
  Column 32 row ratios check passed.
  Column 33 row ratios check passed.
  Column 34 row ratios check passed.
  Column 35 row ratios check passed.
  Column 36 row ratios check passed.
  Column 37 row ratios check passed.
  Column 38 row ratios check passed.
  Column 39 row ratios check passed.
  Column 40 row ratios check passed.
  Column 41 row ratios check passed.
  Column 42 row ratios check passed.
  Column 43 row ratios check passed.
  Column 44 row ratios check passed.
  Column 45 row ratios check passed.
  Column 46 row ratios check passed.
  Column 47 row ratios check passed.
  Column 48 row ratios check passed.
  Column 49 row ratios check passed.

Checking Sector 21.0:
  Overall sum check passed.
  Column sums check passed.
  Column 0 row ratios check passed.
  Column 1 row ratios check passed.
  Column 2 row ratios check passed.
  Column 3 row ratios check passed.
  Column 4 row ratios check passed.
  Column 5 row ratios check passed.
  Column 6 row ratios check passed.
  Column 7 row ratios check passed.
  Column 8 row ratios check passed.
  Column 9 row ratios check passed.
  Column 10 row ratios check passed.
  Column 11 row ratios check passed.
  Column 12 row ratios check passed.
  Column 13 row ratios check passed.
  Column 14 row ratios check passed.
  Column 15 row ratios check passed.
  Column 16 row ratios check passed.
  Column 17 row ratios check passed.
  Column 18 row ratios check passed.
  Column 19 row ratios check passed.
  Column 20 row ratios check passed.
  Column 21 row ratios check passed.
  Column 22 row ratios check passed.
  Column 23 row ratios check passed.
  Column 24 row ratios check passed.
  Column 25 row ratios check passed.
  Column 26 row ratios check passed.
  Column 27 row ratios check passed.
  Column 28 row ratios check passed.
  Column 29 row ratios check passed.
  Column 30 row ratios check passed.
  Column 31 row ratios check passed.
  Column 32 row ratios check passed.
  Column 33 row ratios check passed.
  Column 34 row ratios check passed.
  Column 35 row ratios check passed.
  Column 36 row ratios check passed.
  Column 37 row ratios check passed.
  Column 38 row ratios check passed.
  Column 39 row ratios check passed.
  Column 40 row ratios check passed.
  Column 41 row ratios check passed.
  Column 42 row ratios check passed.
  Column 43 row ratios check passed.
  Column 44 row ratios check passed.
  Column 45 row ratios check passed.
  Column 46 row ratios check passed.
  Column 47 row ratios check passed.
  Column 48 row ratios check passed.
  Column 49 row ratios check passed.

Checking Sector 22.0:
  Overall sum check passed.
  Column sums check passed.
  Column 0 row ratios check passed.
  Column 1 row ratios check passed.
  Column 2 row ratios check passed.
  Column 3 row ratios check passed.
  Column 4 row ratios check passed.
  Column 5 row ratios check passed.
  Column 6 row ratios check passed.
  Column 7 row ratios check passed.
  Column 8 row ratios check passed.
  Column 9 row ratios check passed.
  Column 10 row ratios check passed.
  Column 11 row ratios check passed.
  Column 12 row ratios check passed.
  Column 13 row ratios check passed.
  Column 14 row ratios check passed.
  Column 15 row ratios check passed.
  Column 16 row ratios check passed.
  Column 17 row ratios check passed.
  Column 18 row ratios check passed.
  Column 19 row ratios check passed.
  Column 20 row ratios check passed.
  Column 21 row ratios check passed.
  Column 22 row ratios check passed.
  Column 23 row ratios check passed.
  Column 24 row ratios check passed.
  Column 25 row ratios check passed.
  Column 26 row ratios check passed.
  Column 27 row ratios check passed.
  Column 28 row ratios check passed.
  Column 29 row ratios check passed.
  Column 30 row ratios check passed.
  Column 31 row ratios check passed.
  Column 32 row ratios check passed.
  Column 33 row ratios check passed.
  Column 34 row ratios check passed.
  Column 35 row ratios check passed.
  Column 36 row ratios check passed.
  Column 37 row ratios check passed.
  Column 38 row ratios check passed.
  Column 39 row ratios check passed.
  Column 40 row ratios check passed.
  Column 41 row ratios check passed.
  Column 42 row ratios check passed.
  Column 43 row ratios check passed.
  Column 44 row ratios check passed.
  Column 45 row ratios check passed.
  Column 46 row ratios check passed.
  Column 47 row ratios check passed.
  Column 48 row ratios check passed.
  Column 49 row ratios check passed.

/var/folders/g9/ggrmf_5j6tx4rv5qdhs0slq40000gn/T/ipykernel_45649/2893570910.py:35: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  allocated_total = expected_column_sums[j]

# sector_matrices is between-state, sectors 14-22

# Get rest of matrix.

In [405]:
initial_emp = "/Users/jeffreyohl/Dropbox/SpatialW25/BigDataFiles/pset2/dummy data/L0_initial.csv"

In [406]:
L0_initial = pd.read_csv(initial_emp,header=None)

In [407]:
states = list(pivot_df.index.unique())

In [408]:
states

['Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming']

In [409]:
sectors = range(0,24)

In [410]:
L0_initial

             0
0     0.005356
1     0.000192
2     0.000356
3     0.000306
4     0.000017
...        ...
1145  0.000019
1146  0.000169
1147  0.000155
1148  0.000074
1149  0.000188

[1150 rows x 1 columns]

# countries to states

In [413]:
L_0_intial_vec = L0_initial[0]

In [414]:
states

['Alabama',
 'Alaska',
 'Arizona',
 'Arkansas',
 'California',
 'Colorado',
 'Connecticut',
 'Delaware',
 'Florida',
 'Georgia',
 'Hawaii',
 'Idaho',
 'Illinois',
 'Indiana',
 'Iowa',
 'Kansas',
 'Kentucky',
 'Louisiana',
 'Maine',
 'Maryland',
 'Massachusetts',
 'Michigan',
 'Minnesota',
 'Mississippi',
 'Missouri',
 'Montana',
 'Nebraska',
 'Nevada',
 'New Hampshire',
 'New Jersey',
 'New Mexico',
 'New York',
 'North Carolina',
 'North Dakota',
 'Ohio',
 'Oklahoma',
 'Oregon',
 'Pennsylvania',
 'Rhode Island',
 'South Carolina',
 'South Dakota',
 'Tennessee',
 'Texas',
 'Utah',
 'Vermont',
 'Virginia',
 'Washington',
 'West Virginia',
 'Wisconsin',
 'Wyoming']

In [415]:
L_0_intial_vec

0       0.005356
1       0.000192
2       0.000356
3       0.000306
4       0.000017
          ...
1145    0.000019
1146    0.000169
1147    0.000155
1148    0.000074
1149    0.000188
Name: 0, Length: 1150, dtype: float64

In [416]:
import pandas as pd
import numpy as np

# Example setup:
# states = ["State1", "State2", ..., "State50"]  # length 50
# L0_initial = pd.Series(...)  # length 1150 (50 states × 23 sectors)

# 1) Create a DataFrame with columns: state, sector, share
df = pd.DataFrame({
    "state":  np.repeat(states, 23),
    "sector": np.tile(range(23), len(states)),
    "share":  L_0_intial_vec.values
})

# 2) Filter for sectors 1–22 only
df_filtered = df[df["sector"].between(1, 22)].copy()

# 3) For each sector, compute each state's fraction of total national employment
df_filtered["national_share"] = df_filtered.groupby("sector")["share"].transform(lambda x: x / x.sum())

wide_emp_shares = df_filtered

In [417]:
df_agg_sector_fix.columns

Index(['ExportingCountry', 'ExportingIndustry', 'ImportingCountry',
       'ImportingIndustry', 'Value'],
      dtype='object')

In [418]:
# For each sector (1 - 22) in df_agg_sector_fix

    # For each non-US country, take the trade flow (Into the US) in that sector with the US.
        # multiply by employment share of that state, in that sector [i.e. scale it down using national_share]

# So the goal will be , for each sector, a 37 x 50 matrix (where the 37 is the number of non-US countries)

# Row is origin country, column is destination (state)

In [419]:
import pandas as pd
import numpy as np

# --- Step 1: Set up the sorted lists for states and non-US countries ---

# Get all U.S. states from the employment shares (alphabetically sorted)
states = sorted(wide_emp_shares['state'].unique())

# Get the non-US exporting countries from the trade flow data,
# preserving alphabetical order.
countries = sorted(
    df_agg_sector_fix.loc[
        df_agg_sector_fix['ExportingCountry'] != us_code, 
        'ExportingCountry'
    ].unique()
)

# --- Step 2: Loop over each sector and allocate flows based on employment shares ---
# We'll store the result for each sector in a dictionary.

country_to_state_sector_matrices = {}

# Here we assume the sector values are stored in the 'ExportingIndustry' column.
# You could also use the 'ImportingIndustry' column since they are identical.
for sector in sorted(df_agg_sector_fix['ExportingIndustry'].unique()):
    # Filter for the flows in the current sector, where the US is the importer
    # and the exporting country is not the US.
    df_sector = df_agg_sector_fix[
        (df_agg_sector_fix['ExportingIndustry'] == sector) &
        (df_agg_sector_fix['ImportingCountry'] == us_code) &
        (df_agg_sector_fix['ExportingCountry'] != us_code)
    ]
    
    # In case there are multiple rows per country, sum the flows for each country.
    trade_by_country = df_sector.groupby('ExportingCountry')['Value'].sum()
    
    # Get employment shares for the given sector.
    # We re-index to include all states; missing states get a share of 0.
    emp_shares_sector = wide_emp_shares[
        wide_emp_shares['sector'] == sector
    ].set_index('state')['national_share'].reindex(states, fill_value=0)
    
    # Now we want an outer product: for each exporting country (row) multiply
    # its trade flow value by each state's employment share.
    # For countries that might not appear in the trade_by_country series, we assume a flow of 0.
    trade_vector = pd.Series(
        [trade_by_country.get(country, 0.0) for country in countries], 
        index=countries
    )
    
    # Compute the allocated flows: each cell is trade_value (for the country) * state share.
    # The result will have rows = countries and columns = states.
    allocated = pd.DataFrame(
        np.outer(trade_vector, emp_shares_sector),
        index=countries,
        columns=states
    )
    
    # Save the allocated matrix for this sector.
    country_to_state_sector_matrices[sector] = allocated

# --- sector_matrices now contains, for each sector (key), a DataFrame of shape
#      (number_of_non_US_countries, number_of_states) with the allocated flows.
#
# For example, to view the allocation for sector 2:
print("Sector 2 allocation matrix:")
print(country_to_state_sector_matrices[2])

Sector 2 allocation matrix:
       Alabama        Alaska       Arizona   Arkansas  California  \
1     2.797952  7.249897e-03  2.005241e-01   0.460677    7.819992
2     1.627427  4.216896e-03  1.166346e-01   0.267952    4.548492
3     3.732703  9.671971e-03  2.675159e-01   0.614582   10.432525
4     0.062224  1.612306e-04  4.459458e-03   0.010245    0.173909
5    22.361767  5.794256e-02  1.602626e+00   3.681819   62.498863
6    67.150347  1.739962e-01  4.812541e+00  11.056165  187.678385
7   148.911046  3.858499e-01  1.067218e+01  24.517894  416.191217
8     0.000007  1.765214e-08  4.882384e-07   0.000001    0.000019
9     1.498586  3.883051e-03  1.074009e-01   0.246739    4.188394
10    0.433572  1.123446e-03  3.107327e-02   0.071387    1.211788
11    0.036446  9.443578e-05  2.611988e-03   0.006001    0.101862
12    0.753955  1.953605e-03  5.403452e-02   0.124137    2.107226
13    7.451502  1.930791e-02  5.340353e-01   1.226874   20.826190
14   18.465932  4.784789e-02  1.323419e+00   3.040377   51.610400
15    0.055671  1.442527e-04  3.989868e-03   0.009166    0.155596
16    0.599172  1.552541e-03  4.294156e-02   0.098652    1.674625
17   47.372614  1.227493e-01  3.395107e+00   7.799803  132.401635
18    8.815569  2.284241e-02  6.317955e-01   1.451465   24.638619
19   33.441716  8.665230e-02  2.396706e+00   5.506109   93.466193
20    0.663493  1.719207e-03  4.755134e-02   0.109243    1.854396
21   20.429368  5.293543e-02  1.464135e+00   3.363653   57.098005
22    0.109687  2.842158e-04  7.861090e-03   0.018060    0.306565
23   59.338315  1.537541e-01  4.252667e+00   9.769930  165.844549
24    1.926516  4.991881e-03  1.380698e-01   0.317197    5.384417
25    1.091051  2.827069e-03  7.819357e-02   0.179639    3.049375
26    2.647298  6.859529e-03  1.897269e-01   0.435872    7.398927
27    0.158281  4.101280e-04  1.134368e-02   0.026061    0.442378
28    0.054830  1.420712e-04  3.929531e-03   0.009028    0.153243
29    3.561046  9.227183e-03  2.552136e-01   0.586319    9.952762
30    0.136654  3.540900e-04  9.793734e-03   0.022500    0.381934
31    0.198818  5.151659e-04  1.424891e-02   0.032735    0.555676
32   70.221015  1.819528e-01  5.032610e+00  11.561744  196.260588
33    0.931000  2.412355e-03  6.672304e-02   0.153287    2.602050
34   27.906798  7.231053e-02  2.000028e+00   4.594796   77.996660
35   28.074796  7.274584e-02  2.012069e+00   4.622457   78.466197
36    7.749611  2.008036e-02  5.554002e-01   1.275957   21.659373
37  112.924860  2.926046e-01  8.093115e+00  18.592844  315.613490

        Colorado   Connecticut      Delaware    Florida     Georgia  ...  \
1   2.137312e-01  3.488376e-01  8.255903e-02   1.297843    5.339687  ...
2   1.243166e-01  2.029011e-01  4.802039e-02   0.754889    3.105824  ...
3   2.851354e-01  4.653787e-01  1.101407e-01   1.731432    7.123590  ...
4   4.753172e-03  7.757806e-03  1.836032e-03   0.028863    0.118749  ...
5   1.708180e+00  2.787977e+00  6.598274e-01  10.372609   42.675792  ...
6   5.129510e+00  8.372040e+00  1.981402e+00  31.147998  128.151510  ...
7   1.137508e+01  1.856564e+01  4.393910e+00  69.073075  284.185806  ...
8   5.203953e-07  8.493541e-07  2.010157e-07   0.000003    0.000013  ...
9   1.144746e-01  1.868377e-01  4.421868e-02   0.695126    2.859941  ...
10  3.311986e-02  5.405599e-02  1.279337e-02   0.201114    0.827440  ...
11  2.784022e-03  4.543893e-03  1.075398e-03   0.016905    0.069554  ...
12  5.759341e-02  9.400007e-02  2.224689e-02   0.349725    1.438867  ...
13  5.692086e-01  9.290239e-01  2.198711e-01   3.456414   14.220645  ...
14  1.410584e+00  2.302259e+00  5.448732e-01   8.565508   35.240876  ...
15  4.252653e-03  6.940894e-03  1.642694e-03   0.025823    0.106245  ...
16  4.576983e-02  7.470242e-02  1.767974e-02   0.277929    1.143476  ...
17  3.618720e+00  5.906230e+00  1.397821e+00  21.974006   90.407159  ...
18  6.734076e-01  1.099090e+00  2.601205e-01   4.089142   16.823867  ...
19  2.554560e+00  4.169381e+00  9.867629e-01  15.512094   63.821062  ...
20  5.068322e-02  8.272173e-02  1.957766e-02   0.307764    1.266228  ...
21  1.560568e+00  2.547053e+00  6.028082e-01   9.476257   38.987951  ...
22  8.378847e-03  1.367539e-02  3.236539e-03   0.050879    0.209330  ...
23  4.532761e+00  7.398067e+00  1.750892e+00  27.524351  113.242819  ...
24  1.471636e-01  2.401904e-01  5.684561e-02   0.893623    3.676615  ...
25  8.334365e-02  1.360279e-01  3.219357e-02   0.506089    2.082190  ...
26  2.022229e-01  3.300546e-01  7.811367e-02   1.227961    5.052173  ...
27  1.209081e-02  1.973381e-02  4.670379e-03   0.073419    0.302067  ...
28  4.188342e-03  6.835929e-03  1.617852e-03   0.025433    0.104638  ...
29  2.720228e-01  4.439772e-01  1.050756e-01   1.651808    6.795996  ...
30  1.043878e-02  1.703747e-02  4.032240e-03   0.063388    0.260794  ...
31  1.518739e-02  2.478784e-02  5.866510e-03   0.092223    0.379429  ...
32  5.364074e+00  8.754879e+00  2.072008e+00  32.572341  134.011654  ...
33  7.111763e-02  1.160734e-01  2.747096e-02   0.431849    1.776745  ...
34  2.131757e+00  3.479309e+00  8.234444e-01  12.944697   53.258077  ...
35  2.144590e+00  3.500255e+00  8.284015e-01  13.022624   53.578688  ...
36  5.919806e-01  9.661909e-01  2.286673e-01   3.594693   14.789563  ...
37  8.626154e+00  1.407903e+01  3.332068e+00  52.380717  215.508810  ...

    South Dakota   Tennessee       Texas          Utah       Vermont  \
1   4.355556e-02    2.122530    2.252135  1.427495e-01  8.800997e-02
2   2.533405e-02    1.234568    1.309953  8.303015e-02  5.119092e-02
3   5.810677e-02    2.831633    3.004537  1.904399e-01  1.174127e-01
4   9.686327e-04    0.047203    0.050085  3.174609e-03  1.957255e-03
5   3.481043e-01   16.963664   17.999494  1.140882e+00  7.033924e-01
6   1.045325e+00   50.940336   54.050838  3.425963e+00  2.112223e+00
7   2.318089e+00  112.964103  119.861880  7.597336e+00  4.684017e+00
8   1.060496e-07    0.000005    0.000005  3.475683e-07  2.142877e-07
9   2.332839e-02    1.136829    1.206246  7.645678e-02  4.713821e-02
10  6.749383e-03    0.328908    0.348992  2.212052e-02  1.363805e-02
11  5.673464e-04    0.027648    0.029336  1.859428e-03  1.146401e-03
12  1.173676e-02    0.571951    0.606875  3.846622e-02  2.371574e-02
13  1.159971e-01    5.652719    5.997883  3.801704e-01  2.343880e-01
14  2.874581e-01   14.008279   14.863648  9.421188e-01  5.808484e-01
15  8.666338e-04    0.042232    0.044811  2.840317e-03  1.751152e-03
16  9.327277e-03    0.454533    0.482287  3.056934e-02  1.884704e-02
17  7.374467e-01   35.936924   38.131292  2.416917e+00  1.490112e+00
18  1.372314e-01    6.687502    7.095852  4.497641e-01  2.772949e-01
19  5.205852e-01   25.368927   26.917996  1.706173e+00  1.051914e+00
20  1.032856e-02    0.503327    0.534061  3.385096e-02  2.087027e-02
21  3.180228e-01   15.497744   16.444062  1.042292e+00  6.426085e-01
22  1.707497e-03    0.083209    0.088290  5.596172e-03  3.450231e-03
23  9.237160e-01   45.014119   47.762756  3.027399e+00  1.866495e+00
24  2.998996e-02    1.461458    1.550697  9.828949e-02  6.059883e-02
25  1.698432e-02    0.827672    0.878211  5.566463e-02  3.431914e-02
26  4.121032e-02    2.008243    2.130870  1.350632e-01  8.327111e-02
27  2.463946e-03    0.120072    0.127404  8.075367e-03  4.978740e-03
28  8.535280e-04    0.041594    0.044134  2.797364e-03  1.724670e-03
29  5.543459e-02    2.701414    2.866367  1.816821e-01  1.120132e-01
30  2.127284e-03    0.103666    0.109996  6.971987e-03  4.298468e-03
31  3.094987e-03    0.150824    0.160033  1.014355e-02  6.253845e-03
32  1.093126e+00   53.269748   56.522488  3.582626e+00  2.208812e+00
33  1.449282e-02    0.706258    0.749383  4.749896e-02  2.928473e-02
34  4.344235e-01   21.170132   22.462815  1.423785e+00  8.778121e-01
35  4.370387e-01   21.297575   22.598040  1.432356e+00  8.830965e-01
36  1.206377e-01    5.878864    6.237837  3.953796e-01  2.437651e-01
37  1.757895e+00   85.664938   90.895782  5.761346e+00  3.552067e+00

      Virginia    Washington  West Virginia  Wisconsin       Wyoming
1     1.924089  3.779499e-01   1.314534e-01   0.577293  1.927686e-02
2     1.119145  2.198343e-01   7.645974e-02   0.335782  1.121237e-02
3     2.566896  5.042169e-01   1.753698e-01   0.770158  2.571695e-02
4     0.042790  8.405235e-03   2.923394e-03   0.012838  4.286985e-04
5    15.377685  3.020648e+00   1.050600e+00   4.613839  1.540644e-01
6    46.177787  9.070730e+00   3.154857e+00  13.854938  4.626412e-01
7   102.402784  2.011504e+01   6.996137e+00  30.724388  1.025942e+00
8     0.000005  9.202371e-07   3.200642e-07   0.000001  4.693554e-08
9     1.030544  2.024303e-01   7.040654e-02   0.309199  1.032470e-02
10    0.298157  5.856724e-02   2.037006e-02   0.089458  2.987149e-03
11    0.025063  4.923104e-03   1.712287e-03   0.007520  2.510967e-04
12    0.518478  1.018449e-01   3.542228e-02   0.155561  5.194470e-03
13    5.124231  1.006556e+00   3.500864e-01   1.537447  5.133811e-02
14   12.698607  2.494395e+00   8.675662e-01   3.810023  1.272235e-01
15    0.038284  7.520147e-03   2.615554e-03   0.011487  3.835557e-04
16    0.412037  8.093672e-02   2.815030e-02   0.123625  4.128076e-03
17   32.577084  6.399136e+00   2.225660e+00   9.774255  3.263799e-01
18    6.062269  1.190815e+00   4.141730e-01   1.818891  6.073603e-02
19   22.997118  4.517337e+00   1.571158e+00   6.899933  2.304011e-01
20    0.456269  8.962528e-02   3.117224e-02   0.136897  4.571225e-03
21   14.048818  2.759618e+00   9.598124e-01   4.215133  1.407508e-01
22    0.075430  1.481667e-02   5.153331e-03   0.022631  7.557057e-04
23   40.805627  8.015473e+00   2.787832e+00  12.243104  4.088192e-01
24    1.324822  2.602356e-01   9.051157e-02   0.397493  1.327299e-02
25    0.750291  1.473801e-01   5.125972e-02   0.225113  7.516937e-03
26    1.820487  3.575994e-01   1.243753e-01   0.546209  1.823891e-02
27    0.108846  2.138070e-02   7.436340e-03   0.032658  1.090496e-03
28    0.037705  7.406422e-03   2.576000e-03   0.011313  3.777553e-04
29    2.448852  4.810293e-01   1.673050e-01   0.734740  2.453430e-02
30    0.093974  1.845934e-02   6.420274e-03   0.028195  9.414954e-04
31    0.136723  2.685651e-02   9.340862e-03   0.041022  1.369783e-03
32   48.289416  9.485518e+00   3.299123e+00  14.488500  4.837970e-01
33    0.640228  1.257603e-01   4.374023e-02   0.192091  6.414247e-03
34   19.190879  3.769676e+00   1.311117e+00   5.757930  1.922676e-01
35   19.306407  3.792369e+00   1.319010e+00   5.792592  1.934250e-01
36    5.329233  1.046824e+00   3.640921e-01   1.598955  5.339197e-02
37   77.655892  1.525399e+01   5.305435e+00  23.299462  7.780108e-01

[37 rows x 50 columns]

# states to countries

In [420]:
# --- Step 2: Loop over each sector and allocate US export flows across states ---
# The resulting dictionary will map each sector to a 50 x 37 DataFrame where
# rows represent U.S. states and columns represent non‑US importing countries.
states_to_country_sector_matrices = {}

# We assume the sector indicator is stored in the 'ExportingIndustry' column.
for sector in sorted(df_agg_sector_fix['ExportingIndustry'].unique()):
    # Filter for the flows in the current sector where:
    # - The U.S. is the exporter.
    # - The destination (importing country) is not the U.S.
    df_sector = df_agg_sector_fix[
        (df_agg_sector_fix['ExportingIndustry'] == sector) &
        (df_agg_sector_fix['ExportingCountry'] == us_code) &
        (df_agg_sector_fix['ImportingCountry'] != us_code)
    ]
    
    # In case there are multiple rows per country, sum the export flows for each destination country.
    trade_by_country = df_sector.groupby('ImportingCountry')['Value'].sum()
    
    # Get employment shares for the given sector.
    # We re-index to include all states; missing states get a share of 0.
    emp_shares_sector = wide_emp_shares[
        wide_emp_shares['sector'] == sector
    ].set_index('state')['national_share'].reindex(states, fill_value=0)
    
    # Build a trade vector for the non-US importing countries.
    # For any country not present, we assume an export flow of 0.
    trade_vector = pd.Series(
        [trade_by_country.get(country, 0.0) for country in countries],
        index=countries
    )
    
    # Compute the allocated flows as the outer product of the state employment shares
    # and the export flows for each country.
    # This gives a matrix with rows = states and columns = non-US countries.
    allocated = pd.DataFrame(
        np.outer(emp_shares_sector, trade_vector),
        index=states,
        columns=countries
    )
    
    # Save the allocated matrix for this sector.
    states_to_country_sector_matrices[sector] = allocated

# --- Example: View the allocation for sector 2 ---
print("Sector 2 allocation matrix (rows: states, columns: non-US countries):")
print(states_to_country_sector_matrices[2])

Sector 2 allocation matrix (rows: states, columns: non-US countries):
                       1         2         3         4          5   \
Alabama          8.075171  0.373557  2.409301  0.037562   3.999616
Alaska           0.020924  0.000968  0.006243  0.000097   0.010364
Arizona          0.578733  0.026772  0.172670  0.002692   0.286645
Arkansas         1.329560  0.061505  0.396686  0.006184   0.658528
California      22.569282  1.044054  6.733750  0.104981  11.178520
Colorado         0.616850  0.028535  0.184043  0.002869   0.305524
Connecticut      1.006780  0.046574  0.300382  0.004683   0.498656
Delaware         0.238274  0.011023  0.071091  0.001108   0.118016
Florida          3.745705  0.173276  1.117565  0.017423   1.855240
Georgia         15.410872  0.712906  4.597973  0.071684   7.632974
Hawaii           0.286122  0.013236  0.085367  0.001331   0.141716
Idaho            0.140953  0.006520  0.042054  0.000656   0.069814
Illinois         2.364398  0.109377  0.705439  0.010998   1.171081
Indiana          1.264520  0.058497  0.377281  0.005882   0.626314
Iowa             0.724877  0.033533  0.216274  0.003372   0.359030
Kansas           0.544183  0.025174  0.162362  0.002531   0.269533
Kentucky         2.542164  0.117600  0.758478  0.011825   1.259129
Louisiana        1.029327  0.047617  0.307109  0.004788   0.509823
Maine            1.813407  0.083888  0.541046  0.008435   0.898177
Maryland         1.188283  0.054970  0.354535  0.005527   0.588554
Massachusetts    3.517320  0.162711  1.049424  0.016361   1.742121
Michigan         1.390387  0.064319  0.414834  0.006467   0.688656
Minnesota        0.865342  0.040031  0.258183  0.004025   0.428602
Mississippi      2.348666  0.108649  0.700746  0.010925   1.163289
Missouri         2.266923  0.104868  0.676357  0.010545   1.122802
Montana          0.130572  0.006040  0.038957  0.000607   0.064672
Nebraska         0.233246  0.010790  0.069591  0.001085   0.115526
Nevada           0.212483  0.009829  0.063396  0.000988   0.105242
New Hampshire    0.734445  0.033975  0.219128  0.003416   0.363769
New Jersey       4.835201  0.223676  1.442626  0.022491   2.394865
New Mexico       0.149225  0.006903  0.044523  0.000694   0.073911
New York        13.582699  0.628335  4.052521  0.063180   6.727484
North Carolina  23.713930  1.097005  7.075266  0.110305  11.745462
North Dakota     0.053688  0.002484  0.016018  0.000250   0.026592
Ohio             2.354990  0.108942  0.702633  0.010954   1.166422
Oklahoma         0.775969  0.035896  0.231517  0.003609   0.384336
Oregon           1.071012  0.049545  0.319546  0.004982   0.530470
Pennsylvania     7.615816  0.352307  2.272248  0.035425   3.772098
Rhode Island     1.015864  0.046994  0.303092  0.004725   0.503155
South Carolina  12.132637  0.561255  3.619882  0.056435   6.009271
South Dakota     0.125706  0.005815  0.037505  0.000585   0.062262
Tennessee        6.125835  0.283381  1.827698  0.028494   3.034114
Texas            6.499889  0.300684  1.939301  0.030234   3.219382
Utah             0.411990  0.019059  0.122921  0.001916   0.204058
Vermont          0.254006  0.011750  0.075785  0.001182   0.125808
Virginia         5.553114  0.256887  1.656822  0.025830   2.750446
Washington       1.090801  0.050460  0.325450  0.005074   0.540272
West Virginia    0.379388  0.017550  0.113194  0.001765   0.187910
Wisconsin        1.666127  0.077075  0.497104  0.007750   0.825229
Wyoming          0.055635  0.002574  0.016599  0.000259   0.027556

                        6          7         8         9         10  ...  \
Alabama          69.158765  15.021916  0.002534  0.498425  0.216558  ...
Alaska            0.179200   0.038924  0.000007  0.001291  0.000561  ...
Arizona           4.956480   1.076593  0.000182  0.035721  0.015520  ...
Arkansas         11.386847   2.473327  0.000417  0.082065  0.035656  ...
California      193.291709  41.984727  0.007083  1.393048  0.605257  ...
Colorado          5.282930   1.147501  0.000194  0.038074  0.016543  ...
Connecticut       8.622442   1.872873  0.000316  0.062142  0.027000  ...
Delaware          2.040664   0.443251  0.000075  0.014707  0.006390  ...
Florida          32.079612   6.967985  0.001176  0.231197  0.100451  ...
Georgia         131.984429  28.668225  0.004837  0.951208  0.413284  ...
Hawaii            2.450459   0.532262  0.000090  0.017660  0.007673  ...
Idaho             1.207170   0.262208  0.000044  0.008700  0.003780  ...
Illinois         20.249578   4.398394  0.000742  0.145938  0.063408  ...
Indiana          10.829815   2.352335  0.000397  0.078050  0.033912  ...
Iowa              6.208113   1.348459  0.000227  0.044742  0.019440  ...
Kansas            4.660589   1.012323  0.000171  0.033589  0.014594  ...
Kentucky         21.772038   4.729086  0.000798  0.156910  0.068175  ...
Louisiana         8.815535   1.914815  0.000323  0.063533  0.027604  ...
Maine            15.530688   3.373408  0.000569  0.111929  0.048631  ...
Maryland         10.176897   2.210515  0.000373  0.073345  0.031867  ...
Massachusetts    30.123633   6.543128  0.001104  0.217100  0.094326  ...
Michigan         11.907788   2.586480  0.000436  0.085819  0.037287  ...
Minnesota         7.411113   1.609762  0.000272  0.053412  0.023207  ...
Mississippi      20.114844   4.369128  0.000737  0.144967  0.062986  ...
Missouri         19.414768   4.217065  0.000711  0.139922  0.060794  ...
Montana           1.118265   0.242897  0.000041  0.008059  0.003502  ...
Nebraska          1.997603   0.433898  0.000073  0.014397  0.006255  ...
Nevada            1.819785   0.395274  0.000067  0.013115  0.005698  ...
New Hampshire     6.290060   1.366259  0.000231  0.045332  0.019696  ...
New Jersey       41.410458   8.994730  0.001517  0.298444  0.129669  ...
New Mexico        1.278016   0.277597  0.000047  0.009211  0.004002  ...
New York        116.327276  25.267348  0.004263  0.838368  0.364257  ...
North Carolina  203.094902  44.114070  0.007442  1.463700  0.635954  ...
North Dakota      0.459808   0.099874  0.000017  0.003314  0.001440  ...
Ohio             20.169009   4.380893  0.000739  0.145358  0.063155  ...
Oklahoma          6.645689   1.443504  0.000244  0.047895  0.020810  ...
Oregon            9.172543   1.992360  0.000336  0.066106  0.028722  ...
Pennsylvania     65.224675  14.167396  0.002390  0.470072  0.204239  ...
Rhode Island      8.700234   1.889770  0.000319  0.062702  0.027243  ...
South Carolina  103.908410  22.569857  0.003808  0.748865  0.325370  ...
South Dakota      1.076590   0.233845  0.000039  0.007759  0.003371  ...
Tennessee        52.463924  11.395644  0.001923  0.378106  0.164281  ...
Texas            55.667459  12.091481  0.002040  0.401194  0.174312  ...
Utah              3.528431   0.766408  0.000129  0.025429  0.011049  ...
Vermont           2.175398   0.472516  0.000080  0.015678  0.006812  ...
Virginia         47.558930  10.330235  0.001743  0.342756  0.148922  ...
Washington        9.342028   2.029174  0.000342  0.067328  0.029253  ...
West Virginia     3.249216   0.705760  0.000119  0.023417  0.010174  ...
Wisconsin        14.269329   3.099429  0.000523  0.102839  0.044682  ...
Wyoming           0.476478   0.103495  0.000017  0.003434  0.001492  ...

                       28        29        30        31         32        33  \
Alabama          4.443086  1.191897  0.099813  0.053806   4.087761  0.486745
Alaska           0.011513  0.003088  0.000259  0.000139   0.010592  0.001261
Arizona          0.318428  0.085421  0.007153  0.003856   0.292962  0.034884
Arkansas         0.731545  0.196243  0.016434  0.008859   0.673041  0.080141
California      12.417974  3.331230  0.278966  0.150381  11.424875  1.360402
Colorado         0.339400  0.091047  0.007625  0.004110   0.312258  0.037182
Connecticut      0.553946  0.148601  0.012444  0.006708   0.509646  0.060685
Delaware         0.131102  0.035169  0.002945  0.001588   0.120617  0.014362
Florida          2.060946  0.552867  0.046299  0.024958   1.896127  0.225779
Georgia          8.479304  2.274647  0.190485  0.102684   7.801191  0.928916
Hawaii           0.157429  0.042232  0.003537  0.001906   0.144839  0.017247
Idaho            0.077554  0.020805  0.001742  0.000939   0.071352  0.008496
Illinois         1.300929  0.348985  0.029225  0.015754   1.196890  0.142518
Indiana          0.695759  0.186643  0.015630  0.008426   0.640117  0.076221
Iowa             0.398839  0.106992  0.008960  0.004830   0.366942  0.043693
Kansas           0.299418  0.080322  0.006726  0.003626   0.275473  0.032802
Kentucky         1.398739  0.375224  0.031422  0.016939   1.286878  0.153233
Louisiana        0.566352  0.151929  0.012723  0.006858   0.521059  0.062044
Maine            0.997765  0.267659  0.022414  0.012083   0.917971  0.109306
Maryland         0.653812  0.175391  0.014688  0.007918   0.601525  0.071626
Massachusetts    1.935285  0.519157  0.043476  0.023436   1.780515  0.212012
Michigan         0.765013  0.205221  0.017186  0.009264   0.703832  0.083808
Minnesota        0.476125  0.127725  0.010696  0.005766   0.438048  0.052160
Mississippi      1.292273  0.346663  0.029031  0.015649   1.188926  0.141570
Missouri         1.247297  0.334598  0.028020  0.015105   1.147547  0.136643
Montana          0.071843  0.019272  0.001614  0.000870   0.066097  0.007870
Nebraska         0.128335  0.034427  0.002883  0.001554   0.118072  0.014059
Nevada           0.116912  0.031363  0.002626  0.001416   0.107562  0.012808
New Hampshire    0.404103  0.108404  0.009078  0.004894   0.371786  0.044270
New Jersey       2.660404  0.713677  0.059765  0.032217   2.447644  0.291450
New Mexico       0.082106  0.022026  0.001844  0.000994   0.075540  0.008995
New York         7.473415  2.004809  0.167888  0.090503   6.875745  0.818720
North Carolina  13.047778  3.500180  0.293114  0.158008  12.004311  1.429397
North Dakota     0.029540  0.007924  0.000664  0.000358   0.027178  0.003236
Ohio             1.295753  0.347597  0.029109  0.015692   1.192128  0.141951
Oklahoma         0.426951  0.114533  0.009591  0.005170   0.392806  0.046773
Oregon           0.589288  0.158082  0.013238  0.007136   0.542161  0.064557
Pennsylvania     4.190342  1.124096  0.094135  0.050745   3.855229  0.459056
Rhode Island     0.558944  0.149942  0.012557  0.006769   0.514244  0.061233
South Carolina   6.675568  1.790779  0.149965  0.080841   6.141705  0.731315
South Dakota     0.069165  0.018554  0.001554  0.000838   0.063634  0.007577
Tennessee        3.370531  0.904174  0.075718  0.040817   3.100980  0.369245
Texas            3.576341  0.959385  0.080341  0.043309   3.290331  0.391792
Utah             0.226683  0.060810  0.005092  0.002745   0.208555  0.024833
Vermont          0.139758  0.037491  0.003140  0.001692   0.128581  0.015311
Virginia         3.055411  0.819641  0.068639  0.037001   2.811061  0.334723
Washington       0.600176  0.161002  0.013483  0.007268   0.552178  0.065750
West Virginia    0.208745  0.055998  0.004689  0.002528   0.192051  0.022868
Wisconsin        0.916729  0.245921  0.020594  0.011102   0.843416  0.100429
Wyoming          0.030611  0.008212  0.000688  0.000371   0.028163  0.003353

                      34        35         36          37
Alabama         2.624311  0.719010   3.544351   74.940325
Alaska          0.006800  0.001863   0.009184    0.194181
Arizona         0.188080  0.051530   0.254017    5.370834
Arkansas        0.432087  0.118383   0.583570   12.338769
California      7.334682  2.009560   9.906099  209.450580
Colorado        0.200467  0.054924   0.270747    5.724574
Connecticut     0.327189  0.089643   0.441896    9.343264
Delaware        0.077435  0.021216   0.104583    2.211260
Florida         1.217299  0.333516   1.644063   34.761415
Georgia         5.008305  1.372178   6.764133  143.018112
Hawaii          0.092986  0.025476   0.125585    2.655313
Idaho           0.045807  0.012550   0.061867    1.308088
Illinois        0.768394  0.210525   1.037780   21.942410
Indiana         0.410950  0.112592   0.555022   11.735170
Iowa            0.235574  0.064543   0.318163    6.727101
Kansas          0.176852  0.048454   0.238853    5.050206
Kentucky        0.826166  0.226353   1.115806   23.592145
Louisiana       0.334516  0.091651   0.451792    9.552500
Maine           0.589330  0.161465   0.795940   16.829029
Maryland        0.386174  0.105804   0.521561   11.027669
Massachusetts   1.143077  0.313181   1.543820   32.641919
Michigan        0.451855  0.123799   0.610268   12.903259
Minnesota       0.281223  0.077050   0.379816    8.030670
Mississippi     0.763281  0.209124   1.030875   21.796412
Missouri        0.736716  0.201846   0.994997   21.037811
Montana         0.042434  0.011626   0.057310    1.211750
Nebraska        0.075801  0.020768   0.102376    2.164600
Nevada          0.069054  0.018919   0.093263    1.971916
New Hampshire   0.238684  0.065395   0.322362    6.815899
New Jersey      1.571369  0.430524   2.122264   44.872305
New Mexico      0.048496  0.013287   0.065498    1.384857
New York        4.414176  1.209398   5.961712  126.052047
North Carolina  7.706676  2.111479  10.408508  220.073304
North Dakota    0.017448  0.004780   0.023565    0.498247
Ohio            0.765337  0.209687   1.033651   21.855105
Oklahoma        0.252179  0.069092   0.340588    7.201258
Oregon          0.348063  0.095362   0.470088    9.939352
Pennsylvania    2.475027  0.678109   3.342731   70.677351
Rhode Island    0.330141  0.090452   0.445882    9.427560
South Carolina  3.942927  1.080285   5.325252  112.594984
South Dakota    0.040852  0.011193   0.055175    1.166592
Tennessee       1.990806  0.545442   2.688749   56.849823
Texas           2.112367  0.578747   2.852928   60.321168
Utah            0.133890  0.036683   0.180830    3.823402
Vermont         0.082548  0.022617   0.111488    2.357258
Virginia        1.804680  0.494447   2.437370   51.534779
Washington      0.354494  0.097125   0.478774   10.123007
West Virginia   0.123295  0.033781   0.166521    3.520846
Wisconsin       0.541467  0.148351   0.731296   15.462222
Wyoming         0.018081  0.004954   0.024419    0.516311

[50 rows x 37 columns]

In [421]:
thing = df_agg_sector_fix['ExportingCountry'].unique()

In [422]:
thing

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38])

In [482]:
df_agg_sector_USA_first = df_agg_sector_fix.copy()
df_agg_sector_USA_first['ImportingCountry'] = df_agg_sector_USA_first['ImportingCountry'].replace(38, 0)
df_agg_sector_USA_first['ExportingCountry'] = df_agg_sector_USA_first['ExportingCountry'].replace(38, 0)

In [483]:
df_agg_sector_USA_first

,ExportingCountry,ExportingIndustry,ImportingCountry,ImportingIndustry,Value
0,1,1.0,1,1.0,10851.759013
1,1,1.0,1,2.0,262.228559
2,1,1.0,1,3.0,40.510798
3,1,1.0,1,4.0,2.897519
4,1,1.0,1,5.0,352.067899
...,...,...,...,...,...
698891,0,22.0,0,18.0,214761.185588
698892,0,22.0,0,19.0,25490.798838
698893,0,22.0,0,20.0,241208.476296
698894,0,22.0,0,21.0,116928.130124
698895,0,22.0,0,22.0,826747.505531

In [484]:
# Input costs
country_code = 0
destination_code = 5
source_code = 4


numerator = df_agg_sector_USA_first[(df_agg_sector_USA_first['ImportingCountry'] == country_code) &
                  (df_agg_sector_USA_first['ImportingIndustry'] == destination_code) & 
                  (df_agg_sector_USA_first['ExportingIndustry'] == source_code)].Value.sum()

# Revenues note the importing industry above is the exporting industry below
        #  note that importcountry above is expor|ting country below
denominator = df_agg_sector_USA_first[(df_agg_sector_USA_first['ExportingCountry'] == country_code) &
                  (df_agg_sector_USA_first['ExportingIndustry'] == destination_code)].Value.sum()

# each submatrix corresponds to a country
    # each row corresponds to a source sector
    # each column corresponds to an destination sector 

# values correspond to the quotient of numerator and denominator.

In [ ]:
import numpy as np

# Suppose your DataFrame is named df_agg_sector_USA_first
# Columns: ['ExportingCountry', 'ExportingIndustry',
#           'ImportingCountry', 'ImportingIndustry', 'Value']

# 1) Identify unique countries and sectors
unique_countries = df_agg_sector_USA_first['ImportingCountry'].unique()
# or you might union the set of ExportingCountry and ImportingCountry
# if you need them all to match
unique_sectors = df_agg_sector_USA_first['ExportingIndustry'].unique()
# or union with ImportingIndustry if needed

unique_countries = np.sort(unique_countries)
unique_sectors = np.sort(unique_sectors)

# 2) Prepare a container for the ratio submatrices
#    For each country c, we want a matrix of shape (nSectors, nSectors)
#    submatrix[row=s, col=d].
input_output_submatrices = {}

# 3) Loop over each country and build the ratio matrix
for c in unique_countries:
    print(c)
    # Create an empty matrix for this country
    nSectors = len(unique_sectors)
    ratio_matrix = np.zeros((nSectors, nSectors))
    
    # 4) Compute the ratio for each (source_sector, destination_sector)
    for i, s in enumerate(unique_sectors):
        for j, d in enumerate(unique_sectors):
            
            # numerator: (ImportingCountry == c, ImportingIndustry == d, ExportingIndustry == s)
            numerator = df_agg_sector_USA_first[
                (df_agg_sector_USA_first['ImportingCountry'] == c) &
                (df_agg_sector_USA_first['ImportingIndustry'] == d) &
                (df_agg_sector_USA_first['ExportingIndustry'] == s)
            ]['Value'].sum()
            
            # denominator: (ExportingCountry == c, ExportingIndustry == d)
            denominator = df_agg_sector_USA_first[
                (df_agg_sector_USA_first['ExportingCountry'] == c) &
                (df_agg_sector_USA_first['ExportingIndustry'] == d)
            ]['Value'].sum()
            
            # Avoid division by zero
            ratio =      numerator / denominator if denominator != 0 else 0.0
            ratio_matrix[i, j] = ratio
    
    # Store this ratio matrix for country c
    input_output_submatrices[c] = ratio_matrix

# At the end, country_submatrices[c] holds a 2D

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37

In [510]:
sorted_countries = np.sort(unique_countries)

# 2) Retrieve each country’s ratio matrix from the dictionary
#    (assuming each ratio matrix is shape (nSourceSectors, nDestSectors))
matrices_in_order = [input_output_submatrices[c] for c in sorted_countries]

# 3) Vertically stack them into a single array
#    Result shape: ( (#countries * nSourceSectors), nDestSectors )
big_matrix = np.vstack(matrices_in_order)

df = pd.DataFrame(big_matrix)

# Save to CSV
df.to_csv( out_folder_IO+ "IO.csv",
          index=False,  # Set to True if you want row indices
          header=False)

In [512]:
big_matrix

array([[4.62390654e-01, 2.85271091e-02, 6.88051865e-03, ...,
        3.93990816e-01, 4.44552664e-01, 1.64997995e-02],
       [6.15135192e-04, 2.86312727e-01, 2.09474481e-02, ...,
        5.48224537e-02, 5.96116520e-03, 3.49672403e-03],
       [6.19145224e-02, 3.19497952e-02, 2.40186961e-01, ...,
        2.19464772e-01, 5.78288770e-02, 1.79785397e-02],
       ...,
       [5.42560966e-04, 4.79721883e-04, 5.05550833e-04, ...,
        4.25412669e-01, 5.38591452e-04, 2.61681585e-03],
       [8.59627092e-03, 4.95312316e-03, 3.77954331e-03, ...,
        2.99342702e-01, 1.58570101e-02, 5.14384219e-02],
       [8.58367803e-02, 4.33111462e-02, 2.54746102e-02, ...,
        1.03729822e+00, 7.49545270e-02, 2.28854463e-01]], shape=(836, 22))

In [ ]:
big_matrix

In [511]:
df

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0.462391,0.028527,0.006881,0.001561,0.023108,0.012454,0.002789,0.000991,0.002827,0.001233,...,0.007573,0.002816,0.000706,0.000604,0.000155,0.000345,0.250880,0.393991,0.444553,0.016500
1,0.000615,0.286313,0.020947,0.000375,0.000659,0.012655,0.003106,0.000203,0.008059,0.000341,...,0.007689,0.006099,0.000353,0.002166,0.000130,0.000156,0.002147,0.054822,0.005961,0.003497
2,0.061915,0.031950,0.240187,0.000848,0.012462,0.037490,0.017792,0.011917,0.026871,0.010877,...,0.025331,0.132194,0.007789,0.018176,0.007218,0.005854,0.033169,0.219465,0.057829,0.017979
3,0.011435,0.013677,0.022652,0.053036,0.049955,0.024673,0.016720,0.009733,0.019214,0.007202,...,0.009417,0.209156,0.209483,0.002151,0.001748,0.003342,0.031574,0.201053,0.021839,0.049078
4,0.025833,0.177195,0.062952,0.025617,0.398074,0.317573,0.049218,0.022449,0.046191,0.026985,...,0.009164,0.046031,0.004313,0.007365,0.001591,0.007411,0.026177,0.670713,0.017752,0.020207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831,0.002532,0.001681,0.001256,0.000239,0.000415,0.001589,0.000765,0.000639,0.002048,0.001056,...,0.066523,0.004292,0.005923,0.021035,0.034546,0.064989,0.156848,0.218547,0.034304,0.029173
832,0.001284,0.000543,0.000511,0.000181,0.000674,0.000439,0.000421,0.000323,0.001270,0.000560,...,0.002716,0.003076,0.003267,0.003864,0.007373,0.001544,0.377160,0.150961,0.001386,0.011239
833,0.000543,0.000480,0.000506,0.000546,0.000296,0.000176,0.000335,0.000394,0.000942,0.000418,...,0.000844,0.001559,0.000868,0.001475,0.000656,0.000707,0.012466,0.425413,0.000539,0.002617
834,0.008596,0.004953,0.003780,0.000686,0.005605,0.003771,0.004070,0.002396,0.007981,0.004925,...,0.010660,0.018221,0.026452,0.007338,0.027141,0.007889,0.293505,0.299343,0.015857,0.051438
835,0.085837,0.043311,0.025475,0.011444,0.050600,0.035086,0.022211,0.019377,0.058853,0.049447,...,0.208796,0.194011,0.082555,0.147333,0.135599,0.128654,0.736247,1.037298,0.074955,0.228854

In [471]:
df_agg_sector_fix.ImportingCountry.unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38])

In [451]:
numerator/denominator

/var/folders/g9/ggrmf_5j6tx4rv5qdhs0slq40000gn/T/ipykernel_45649/2158541987.py:1: RuntimeWarning: invalid value encountered in scalar divide
  numerator/denominator

np.float64(nan)

# shitty value-added calculation, although this should be close to correct for the 
# 37 non-US countries?
# gamma_nj's

In [ ]:
import numpy as np

# Suppose 'big_matrix' is your original 836x22 array.
# 1) Reshape into 38 submatrices of shape 22x22
big_matrix_reshaped = big_matrix.reshape(38, 22, 22)

# 2) Sum each submatrix along the "row" axis => column sums
#    shape of col_sums will be (38, 22), i.e. one 22-element sum-vector per submatrix
one_minus_col_sums = 1-big_matrix_reshaped.sum(axis=1)

# 3) Construct the final 22x87 matrix
final_mat = np.zeros((22, 87))

# -- (a) First 50 columns all come from the first submatrix’s column sums
#       Repeat col_sums[0] (shape (22,)) across 50 columns
first_submatrix_sums = one_minus_col_sums[0]  # shape (22,)
final_mat[:, :50] = np.repeat(first_submatrix_sums[:, None], 50, axis=1)

# -- (b) Next 37 columns come from submatrices 2..38 (i.e. col_sums[1..37] in 0-based index)
for i in range(37):
    final_mat[:, 50 + i] = one_minus_col_sums[i + 1]

# final_mat is now the 22x87 matrix you described

# Gluing

In [423]:
len(sector_matrices)

9

In [424]:
len(scaled_trade_flows)

13

In [425]:
df_agg_sector_fix.columns

Index(['ExportingCountry', 'ExportingIndustry', 'ImportingCountry',
       'ImportingIndustry', 'Value'],
      dtype='object')

In [426]:
# matrix-ise df_agg_sector_fix

In [427]:
import pandas as pd
import numpy as np

# 1. Filter out rows where ExportingCountry=38 or ImportingCountry=38
df_filtered = df_agg_sector_fix.query(
    "ExportingCountry != 38 & ImportingCountry != 38"
)

intl_sector_matrices = {}

# 2. Loop over each sector
for sector in range(1, 23):
    # 2a. Subset rows for this ExportingIndustry
    df_sector = df_filtered[df_filtered["ExportingIndustry"] == sector]
    
    # 2b. Pivot with aggfunc='sum' so that each (ExportingCountry, ImportingCountry)
    #     collapses into a single Value
    pivoted = df_sector.pivot_table(
        index="ExportingCountry",
        columns="ImportingCountry",
        values="Value",
        aggfunc="sum",
        fill_value=0
    )
    
    # 2c. Reindex to ensure the table is 1..37 × 1..37
    pivoted = pivoted.reindex(index=range(1, 38),
                              columns=range(1, 38),
                              fill_value=0)
    
    # 2d. Convert to NumPy array
    mat = pivoted.to_numpy()
    
    intl_sector_matrices[sector] = mat

# all of the belows are dicts of matrices. where the key is the sector

# Country-Country Trade
#### intl_sector_matrices    -  37x37 non-US trade for each of 22 sectors. sorted

# State-State Trade
#### scaled_trade_flows       -  50x50 for non-service sectors, which we have CFS data on (first 13)
#### sector_matrices - 50x50 for services sectors (14-22) 

# State-Country and Country-State trade
#### country_to_state_sector_matrices - 37 x 50 of countries to states for all 22 sectors, sorted.
#### states_to_country_sector_matrices  50 x 37 of state to country for all 22 sectors, sorted.

In [434]:
sector_keys = range(1,23)

In [435]:
import numpy as np

# Assuming sector_keys is a list of the sector keys in the correct order
final_matrix_list = []

for i, key in enumerate(sector_keys):
    # Select the appropriate state-to-state matrix based on the sector type
    if i < 13:  # sectors 1 to 13: non-services
        state_state = scaled_trade_flows[key]  # shape (50,50)
    else:       # sectors 14 to 22: services
        state_state = sector_matrices[key]     # shape (50,50)
    
    # Retrieve the state-to-country, country-to-state, and country-to-country matrices
    state_country   = states_to_country_sector_matrices[key]   # shape (50,37)
    country_state   = country_to_state_sector_matrices[key]      # shape (37,50)
    country_country = intl_sector_matrices[key]                # shape (37,37)
    
    # Create the 87x87 matrix for the current sector
    sector_matrix = np.block([
        [state_state,   state_country],
        [country_state, country_country]
    ])
    
    final_matrix_list.append(sector_matrix)

# Vertically stack all 22 sector matrices to form the final 1914x87 matrix
final_matrix = np.vstack(final_matrix_list)

In [441]:
df = pd.DataFrame(final_matrix)

# Save to CSV
df.to_csv(out_folder + "X_in_j.csv",
          index=False,  # Set to True if you want row indices
          header=False)

In [ ]:
scaled_trade_flows

In [430]:
sector_matrices

{np.float64(14.0): array([[1.61044663e+03, 2.21676006e-02, 1.30936628e+01, ...,
         3.08129649e+00, 1.93301478e+01, 3.17735609e-01],
        [0.00000000e+00, 2.33476559e+02, 5.17244015e-02, ...,
         0.00000000e+00, 1.47784004e-02, 0.00000000e+00],
        [8.22417984e+00, 2.88178808e-01, 1.51018996e+03, ...,
         8.12812023e-02, 9.78330108e+00, 1.85468925e+00],
        ...,
        [1.19705043e+00, 7.38920021e-03, 1.09360163e+00, ...,
         3.34213526e+02, 3.46553490e+00, 1.03448803e-01],
        [2.32316455e+01, 5.46800816e-01, 2.28547963e+01, ...,
         5.71924096e+00, 2.04646856e+03, 1.26355324e+00],
        [5.91136017e-02, 7.38920021e-03, 1.07882323e+00, ...,
         7.38920021e-03, 6.57638819e-01, 1.54338225e+02]], shape=(50, 50)),
 np.float64(15.0): array([[4.34792782e+03, 5.98486940e-02, 3.53506286e+01, ...,
         8.31896847e+00, 5.21880612e+01, 8.57831281e-01],
        [0.00000000e+00, 6.30346395e+02, 1.39646953e-01, ...,
         0.00000000e+00, 3.98991294e-02, 0.00000000e+00],
        [2.22038655e+01, 7.78033023e-01, 4.07725213e+03, ...,
         2.19445211e-01, 2.64132236e+01, 5.00734073e+00],
        ...,
        [3.23182948e+00, 1.99495647e-02, 2.95253557e+00, ...,
         9.02318810e+02, 9.35634583e+00, 2.79293906e-01],
        [6.27214314e+01, 1.47626779e+00, 6.17040036e+01, ...,
         1.54409631e+01, 5.52511174e+03, 3.41137556e+00],
        [1.59596517e-01, 1.99495647e-02, 2.91263644e+00, ...,
         1.99495647e-02, 1.77551126e+00, 4.16686557e+02]], shape=(50, 50)),
 np.float64(16.0): array([[6.03771448e+03, 8.31084004e-02, 4.90893619e+01, ...,
         1.15520677e+01, 7.24705252e+01, 1.19122041e+00],
        [0.00000000e+00, 8.75325376e+02, 1.93919601e-01, ...,
         0.00000000e+00, 5.54056003e-02, 0.00000000e+00],
        [3.08332166e+01, 1.08040921e+00, 5.66184289e+03, ...,
         3.04730802e-01, 3.66785074e+01, 6.95340284e+00],
        ...,
        [4.48785362e+00, 2.77028001e-02, 4.10001442e+00, ...,
         1.25299765e+03, 1.29926133e+01, 3.87839202e-01],
        [8.70976037e+01, 2.05000721e+00, 8.56847609e+01, ...,
         2.14419673e+01, 7.67240131e+03, 4.73717883e+00],
        [2.21622401e-01, 2.77028001e-02, 4.04460882e+00, ...,
         2.77028001e-02, 2.46554921e+00, 5.78628387e+02]], shape=(50, 50)),
 np.float64(17.0): array([[8.32992506e+03, 1.14660398e-01, 6.77260753e+01, ...,
         1.59377954e+01, 9.99838673e+01, 1.64346571e+00],
        [0.00000000e+00, 1.20764154e+03, 2.67540929e-01, ...,
         0.00000000e+00, 7.64402655e-02, 0.00000000e+00],
        [4.25390078e+01, 1.49058518e+00, 7.81135430e+03, ...,
         4.20421461e-01, 5.06034558e+01, 9.59325333e+00],
        ...,
        [6.19166151e+00, 3.82201328e-02, 5.65657965e+00, ...,
         1.72869661e+03, 1.79252423e+01, 5.35081859e-01],
        [1.20164097e+02, 2.82828983e+00, 1.18214871e+02, ...,
         2.95823828e+01, 1.05852187e+04, 6.53564270e+00],
        [3.05761062e-01, 3.82201328e-02, 5.58013938e+00, ...,
         3.82201328e-02, 3.40159182e+00, 7.98303913e+02]], shape=(50, 50)),
 np.float64(18.0): array([[6.03506225e+03, 8.30718929e-02, 4.90677981e+01, ...,
         1.15469931e+01, 7.24386906e+01, 1.19069713e+00],
        [0.00000000e+00, 8.74940866e+02, 1.93834417e-01, ...,
         0.00000000e+00, 5.53812619e-02, 0.00000000e+00],
        [3.08196723e+01, 1.07993461e+00, 5.65935577e+03, ...,
         3.04596941e-01, 3.66623954e+01, 6.95034837e+00],
        ...,
        [4.48588222e+00, 2.76906310e-02, 4.09821338e+00, ...,
         1.25244724e+03, 1.29869059e+01, 3.87668833e-01],
        [8.70593437e+01, 2.04910669e+00, 8.56471216e+01, ...,
         2.14325484e+01, 7.66903101e+03, 4.73509789e+00],
        [2.21525048e-01, 2.76906310e-02, 4.04283212e+00, ...,
         2.76906310e-02, 2.46446616e+00, 5.78374209e+02]], shape=(50, 50)),
 np.float64(19.0): array([[3.24466000e+02, 4.46623476e-03, 2.63805600e+00, ...,
         6.20806632e-01, 3.89455671e+00, 6.40160316e-02],
        [0.00000000e+00, 4.70398732e+01, 1.04212144e-02, ...,
         0.00000000e+00, 2.97748984e-03, 0.00000000e+00],
        [1.65697310e+00, 5.80610519e-02, 3.04266709e+02, ...,
         1.63761941e-02, 1.97109827e+00, 3.73674975e-01],
        ...,
        [2.41176677e-01, 1.48874492e-03, 2.20334248e-01, ...,
         6.73359327e+01, 6.98221367e-01, 2.08424289e-02],
        [4.68061403e+00, 1.10167124e-01, 4.60468804e+00, ...,
         1.15228857e+00, 4.12313861e+02, 2.54575381e-01],
        [1.19099594e-02, 1.48874492e-03, 2.17356758e-01, ...,
         1.48874492e-03, 1.32498298e-01, 3.10954151e+01]], shape=(50, 50)),
 np.float64(20.0): array([[4.39174025e+02, 6.04517667e-03, 3.57068436e+00, ...,
         8.40279558e-01, 5.27139406e+00, 8.66475323e-02],
        [0.00000000e+00, 6.36698158e+01, 1.41054122e-02, ...,
         0.00000000e+00, 4.03011778e-03, 0.00000000e+00],
        [2.24276055e+00, 7.85872968e-02, 4.11833706e+02, ...,
         2.21656478e-02, 2.66793797e+00, 5.05779782e-01],
        ...,
        [3.26439540e-01, 2.01505889e-03, 2.98228716e-01, ...,
         9.11411137e+01, 9.45062620e-01, 2.82108245e-02],
        [6.33534515e+00, 1.49114358e-01, 6.23257715e+00, ...,
         1.55965558e+00, 5.58078620e+02, 3.44575070e-01],
        [1.61204711e-02, 2.01505889e-03, 2.94198598e-01, ...,
         2.01505889e-03, 1.79340241e-01, 4.20885351e+01]], shape=(50, 50)),
 np.float64(21.0): array([[1.42587045e+03, 1.96269321e-02, 1.15929746e+01, ...,
         2.72814357e+00, 1.71146848e+01, 2.81319361e-01],
        [0.00000000e+00, 2.06717392e+02, 4.57961750e-02, ...,
         0.00000000e+00, 1.30846214e-02, 0.00000000e+00],
        [7.28159183e+00, 2.55150118e-01, 1.33710438e+03, ...,
         7.19654179e-02, 8.66201939e+00, 1.64211999e+00],
        ...,
        [1.05985434e+00, 6.54231072e-03, 9.68261986e-01, ...,
         2.95908714e+02, 3.06834373e+00, 9.15923500e-02],
        [2.05690249e+01, 4.84130993e-01, 2.02353670e+01, ...,
         5.06374849e+00, 1.81191912e+03, 1.11873513e+00],
        [5.23384857e-02, 6.54231072e-03, 9.55177365e-01, ...,
         6.54231072e-03, 5.82265654e-01, 1.36649244e+02]], shape=(50, 50)),
 np.float64(22.0): array([[2.05458476e+04, 2.82811076e-01, 1.67047076e+02, ...,
         3.93107396e+01, 2.46611258e+02, 4.05362543e+00],
        [0.00000000e+00, 2.97866053e+03, 6.59892511e-01, ...,
         0.00000000e+00, 1.88540717e-01, 0.00000000e+00],
        [1.04922909e+02, 3.67654399e+00, 1.92667874e+04, ...,
         1.03697395e+00, 1.24813955e+02, 2.36618600e+01],
        ...,
        [1.52717981e+01, 9.42703587e-02, 1.39520131e+01, ...,
         4.26384833e+03, 4.42127983e+01, 1.31978502e+00],
        [2.96386008e+02, 6.97600655e+00, 2.91578220e+02, ...,
         7.29652577e+01, 2.61085529e+04, 1.61202313e+01],
        [7.54162870e-01, 9.42703587e-02, 1.37634724e+01, ...,
         9.42703587e-02, 8.39006193e+00, 1.96902498e+03]], shape=(50, 50))}

In [428]:
states_to_country_sector_matrices

{np.float64(1.0):                        1         2          3         4          5   \
 Alabama          5.306458  0.652718   4.896340  0.039092   7.315907
 Alaska           0.760040  0.093488   0.701299  0.005599   1.047852
 Arizona          1.833968  0.225586   1.692227  0.013511   2.528454
 Arkansas         7.846197  0.965118   7.239791  0.057802  10.817394
 California      28.644636  3.523420  26.430790  0.211021  39.491786
 Colorado         3.819954  0.469872   3.524723  0.028141   5.266494
 Connecticut      1.820741  0.223959   1.680022  0.013413   2.510219
 Delaware         1.127228  0.138654   1.040108  0.008304   1.554087
 Florida          8.031765  0.987943   7.411017  0.059169  11.073233
 Georgia         10.936873  1.345285  10.091600  0.080570  15.078448
 Hawaii           0.932975  0.114760   0.860868  0.006873   1.286274
 Idaho            2.826368  0.347656   2.607927  0.020821   3.896657
 Illinois        15.635917  1.923289  14.427470  0.115188  21.556926
 Indiana          5.586990  0.687225   5.155190  0.041159   7.702670
 Iowa             8.516212  1.047533   7.858023  0.062738  11.741130
 Kansas           4.976789  0.612168   4.592150  0.036663   6.861399
 Kentucky         4.862292  0.598084   4.486502  0.035820   6.703544
 Louisiana        3.042533  0.374245   2.807386  0.022414   4.194679
 Maine            1.219223  0.149970   1.124993  0.008982   1.680918
 Maryland         3.270341  0.402267   3.017587  0.024092   4.508753
 Massachusetts    3.614825  0.444640   3.335448  0.026630   4.983687
 Michigan         6.819254  0.838799   6.292217  0.050236   9.401569
 Minnesota        8.757235  1.077180   8.080418  0.064513  12.073424
 Mississippi      3.987562  0.490488   3.679377  0.029376   5.497571
 Missouri         8.413164  1.034857   7.762939  0.061979  11.599061
 Montana          0.387720  0.047691   0.357755  0.002856   0.534542
 Nebraska         5.165309  0.635356   4.766100  0.038052   7.121308
 Nevada           0.803273  0.098806   0.741191  0.005918   1.107456
 New Hampshire    0.627577  0.077195   0.579073  0.004623   0.865227
 New Jersey       6.393822  0.786469   5.899665  0.047102   8.815034
 New Mexico       0.868026  0.106771   0.800939  0.006395   1.196730
 New York        11.970741  1.472455  11.045563  0.088187  16.503820
 North Carolina   9.959289  1.225038   9.189569  0.073369  13.730672
 North Dakota     0.909286  0.111846   0.839011  0.006699   1.253615
 Ohio            10.259354  1.261947   9.466444  0.075579  14.144366
 Oklahoma         3.274700  0.402803   3.021609  0.024124   4.514763
 Oregon           3.332335  0.409892   3.074790  0.024549   4.594223
 Pennsylvania    14.266863  1.754889  13.164226  0.105102  19.669438
 Rhode Island     0.583157  0.071731   0.538087  0.004296   0.803987
 South Carolina   2.910654  0.358024   2.685700  0.021442   4.012861
 South Dakota     1.140259  0.140257   1.052132  0.008400   1.572052
 Tennessee        6.257611  0.769715   5.773982  0.046099   8.627243
 Texas           15.456474  1.901216  14.261896  0.113866  21.309531
 Utah             1.950837  0.239962   1.800064  0.014372   2.689581
 Vermont          0.576643  0.070930   0.532076  0.004248   0.795007
 Virginia         7.574742  0.931728   6.989316  0.055802  10.443145
 Washington       5.406939  0.665078   4.989055  0.039832   7.454439
 West Virginia    1.092484  0.134381   1.008050  0.008048   1.506186
 Wisconsin       10.917147  1.342859  10.073398  0.080425  15.051251
 Wyoming          0.182607  0.022462   0.168494  0.001345   0.251757

                         6           7         8         9          10  ...  \
 Alabama          62.710099   48.292884  0.002028  0.198242   2.281023  ...
 Alaska            8.981921    6.916954  0.000291  0.028394   0.326709  ...
 Arizona          21.673270   16.690529  0.000701  0.068515   0.788346  ...
 Arkansas         92.723958   71.406479  0.002999  0.293123   3.372750  ...
 California      338.513572  260.688422  0.010950  1.070125  12.313125  ...
 Colorado         45.143055   34.764549  0.001460  0.142708   1.642038  ...
 Connecticut      21.516964   16.570158  0.000696  0.068020   0.782660  ...
 Delaware         13.321238   10.258651  0.000431  0.042112   0.484548  ...
 Florida          94.916945   73.095292  0.003070  0.300056   3.452518  ...
 Georgia         129.248633   99.534036  0.004181  0.408587   4.701302  ...
 Hawaii           11.025611    8.490795  0.000357  0.034855   0.401047  ...
 Idaho            33.401153   25.722141  0.001080  0.105589   1.214937  ...
 Illinois        184.780499  142.298982  0.005977  0.584137   6.721223  ...
 Indiana          66.025337   50.845941  0.002136  0.208722   2.401612  ...
 Iowa            100.641990   77.504135  0.003255  0.318154   3.660761  ...
 Kansas           58.814173   45.292642  0.001902  0.185926   2.139312  ...
 Kentucky         57.461081   44.250629  0.001859  0.181649   2.090095  ...
 Louisiana        35.955725   27.689410  0.001163  0.113665   1.307857  ...
 Maine            14.408406   11.095876  0.000466  0.045549   0.524093  ...
 Maryland         38.647888   29.762638  0.001250  0.122176   1.405782  ...
 Massachusetts    42.718901   32.897715  0.001382  0.135045   1.553861  ...
 Michigan         80.587865   62.060506  0.002607  0.254758   2.931311  ...
 Minnesota       103.490330   79.697634  0.003347  0.327158   3.764367  ...
 Mississippi      47.123786   36.289905  0.001524  0.148970   1.714085  ...
 Missouri         99.424207   76.566324  0.003216  0.314304   3.616466  ...
 Montana           4.581960    3.528556  0.000148  0.014485   0.166665  ...
 Nebraska         61.042047   47.008322  0.001974  0.192969   2.220349  ...
 Nevada            9.492836    7.310408  0.000307  0.030009   0.345293  ...
 New Hampshire     7.416508    5.711434  0.000240  0.023445   0.269769  ...
 New Jersey       75.560233   58.188739  0.002444  0.238865   2.748435  ...
 New Mexico       10.258066    7.899710  0.000332  0.032428   0.373128  ...
 New York        141.466563  108.943033  0.004576  0.447211   5.145718  ...
 North Carolina  117.695837   90.637259  0.003807  0.372066   4.281080  ...
 North Dakota     10.745668    8.275211  0.000348  0.033970   0.390864  ...
 Ohio            121.241916   93.368085  0.003922  0.383276   4.410065  ...
 Oklahoma         38.699404   29.802310  0.001252  0.122338   1.407656  ...
 Oregon           39.380514   30.326832  0.001274  0.124492   1.432431  ...
 Pennsylvania    168.601433  129.839526  0.005454  0.532991   6.132725  ...
 Rhode Island      6.891574    5.307183  0.000223  0.021786   0.250675  ...
 South Carolina   34.397224   26.489213  0.001113  0.108738   1.251168  ...
 South Dakota     13.475229   10.377239  0.000436  0.042599   0.490149  ...
 Tennessee        73.950543   56.949121  0.002392  0.233776   2.689884  ...
 Texas           182.659894  140.665910  0.005908  0.577433   6.644088  ...
 Utah             23.054402   17.754135  0.000746  0.072881   0.838583  ...
 Vermont           6.814594    5.247901  0.000220  0.021543   0.247875  ...
 Virginia         89.515989   68.936030  0.002895  0.282982   3.256063  ...
 Washington       63.897560   49.207345  0.002067  0.201996   2.324216  ...
 West Virginia    12.910648    9.942456  0.000418  0.040814   0.469613  ...
 Wisconsin       129.015510   99.354509  0.004173  0.407850   4.692822  ...
 Wyoming           2.157996    1.661867  0.000070  0.006822   0.078495  ...

                       28         29        30        31         32        33  \
 Alabama         0.858368   2.828270  0.018047  0.012162  14.738730  0.238218
 Alaska          0.122943   0.405091  0.002585  0.001742   2.111017  0.034120
 Arizona         0.296661   0.977480  0.006237  0.004203   5.093860  0.082331
 Arkansas        1.269193   4.181916  0.026685  0.017983  21.792875  0.352232
 California      4.633529  15.267200  0.097420  0.065652  79.560711  1.285917
 Colorado        0.617912   2.035983  0.012992  0.008755  10.609954  0.171486
 Connecticut     0.294521   0.970430  0.006192  0.004173   5.057123  0.081737
 Delaware        0.182339   0.600797  0.003834  0.002584   3.130885  0.050604
 Florida         1.299211   4.280821  0.027316  0.018408  22.308292  0.360563
 Georgia         1.769138   5.829204  0.037196  0.025067  30.377255  0.490979
 Hawaii          0.150917   0.497263  0.003173  0.002138   2.591345  0.041883
 Idaho           0.457191   1.506415  0.009612  0.006478   7.850260  0.126882
 Illinois        2.529251   8.333730  0.053178  0.035837  43.428887  0.701929
 Indiana         0.903746   2.977789  0.019001  0.012805  15.517909  0.250812
 Iowa            1.377574   4.539024  0.028964  0.019519  23.653847  0.382310
 Kansas          0.805041   2.652560  0.016926  0.011407  13.823072  0.223418
 Kentucky        0.786520   2.591535  0.016537  0.011144  13.505055  0.218278
 Louisiana       0.492157   1.621628  0.010348  0.006973   8.450660  0.136586
 Maine           0.197220   0.649829  0.004147  0.002794   3.386402  0.054733
 Maryland        0.529007   1.743047  0.011122  0.007495   9.083398  0.146812
 Massachusetts   0.584731   1.926652  0.012294  0.008285  10.040206  0.162277
 Michigan        1.103076   3.634569  0.023192  0.015629  18.940534  0.306130
 Minnesota       1.416562   4.667487  0.029783  0.020071  24.323291  0.393130
 Mississippi     0.645024   2.125316  0.013562  0.009139  11.075485  0.179010
 Missouri        1.360905   4.484102  0.028613  0.019283  23.367632  0.377684
 Montana         0.062717   0.206650  0.001319  0.000889   1.076896  0.017406
 Nebraska        0.835535   2.753039  0.017567  0.011839  14.346688  0.231881
 Nevada          0.129937   0.428134  0.002732  0.001841   2.231097  0.036061
 New Hampshire   0.101516   0.334490  0.002134  0.001438   1.743099  0.028173
 New Jersey      1.034258   3.407820  0.021745  0.014654  17.758892  0.287032
 New Mexico      0.140411   0.462646  0.002952  0.001989   2.410949  0.038967
 New York        1.936376   6.380241  0.040712  0.027436  33.248830  0.537391
 North Carolina  1.611005   5.308165  0.033872  0.022826  27.662006  0.447093
 North Dakota    0.147085   0.484637  0.003092  0.002084   2.525550  0.040820
 Ohio            1.659543   5.468096  0.034892  0.023514  28.495440  0.460564
 Oklahoma        0.529712   1.745370  0.011137  0.007505   9.095506  0.147008
 Oregon          0.539035   1.776089  0.011333  0.007638   9.255587  0.149595
 Pennsylvania    2.307794   7.604043  0.048522  0.032699  39.626328  0.640469
 Rhode Island    0.094331   0.310815  0.001983  0.001337   1.619724  0.026179
 South Carolina  0.470825   1.551339  0.009899  0.006671   8.084366  0.130665
 South Dakota    0.184447   0.607742  0.003878  0.002613   3.167078  0.051189
 Tennessee       1.012225   3.335221  0.021282  0.014342  17.380567  0.280917
 Texas           2.500224   8.238089  0.052567  0.035425  42.930483  0.693873
 Utah            0.315566   1.039770  0.006635  0.004471   5.418467  0.087577
 Vermont         0.093277   0.307343  0.001961  0.001322   1.601631  0.025887
 Virginia        1.225283   4.037234  0.025762  0.017361  21.038907  0.340046
 Washington      0.874621   2.881825  0.018389  0.012392  15.017818  0.242729
 West Virginia   0.176719   0.582279  0.003716  0.002504   3.034384  0.049044
 Wisconsin       1.765947   5.818690  0.037129  0.025022  30.322464  0.490093
 Wyoming         0.029538   0.097327  0.000621  0.000419   0.507193  0.008198

                        34         35         36          37
 Alabama          5.805091   6.211420   5.437187   78.662293
 Alaska           0.831459   0.889657   0.778764   11.266742
 Arizona          2.006300   2.146732   1.879149   27.186516
 Arkansas         8.583482   9.184286   8.039494  116.311076
 California      31.336293  33.529688  29.350320  424.624647
 Colorado         4.178905   4.471409   3.914062   56.626544
 Connecticut      1.991831   2.131250   1.865597   26.990448
 Delaware         1.233151   1.319465   1.154998   16.709894
 Florida          8.786487   9.401501   8.229634  119.061915
 Georgia         11.964581  12.802046  11.206312  162.126897
 Hawaii           1.020644   1.092084   0.955959   13.830306
 Idaho            3.091954   3.308376   2.895998   41.897737
 Illinois        17.105181  18.302464  16.021121  231.784958
 Indiana          6.111983   6.539794   5.724630   82.820861
 Iowa             9.316456   9.968565   8.726015  126.243297
 Kansas           5.444444   5.825530   5.099396   73.775321
 Kentucky         5.319188   5.691506   4.982078   72.078030
 Louisiana        3.328431   3.561406   3.117488   45.102141
 Maine            1.333790   1.427149   1.249260   18.073616
 Maryland         3.577645   3.828064   3.350908   48.479137
 Massachusetts    3.954500   4.231297   3.703879   53.585735
 Michigan         7.460040   7.982209   6.987252  101.087805
 Minnesota        9.580128  10.250692   8.972977  129.816198
 Mississippi      4.362262   4.667600   4.085798   59.111133
 Missouri         9.203726   9.847944   8.620429  124.715735
 Montana          0.424153   0.453842   0.397272    5.747519
 Nebraska         5.650679   6.046200   5.292561   76.569921
 Nevada           0.878754   0.940263   0.823062   11.907623
 New Hampshire    0.686548   0.734603   0.643037    9.303119
 New Jersey       6.994631   7.484223   6.551339   94.781243
 New Mexico       0.949592   1.016059   0.889411   12.867513
 New York        13.095598  14.012229  12.265650  177.452824
 North Carolina  10.895135  11.657745  10.204644  147.635302
 North Dakota     0.994729   1.064356   0.931687   13.479151
 Ohio            11.223397  12.008983  10.512102  152.083432
 Oklahoma         3.582414   3.833167   3.355375   48.543757
 Oregon           3.645465   3.900631   3.414429   49.398129
 Pennsylvania    15.607480  16.699932  14.618339  211.490262
 Rhode Island     0.637955   0.682609   0.597524    8.644652
 South Carolina   3.184160   3.407037   2.982361   43.147189
 South Dakota     1.247406   1.334718   1.168350   16.903058
 Tennessee        6.845622   7.324784   6.411773   92.762080
 Texas           16.908876  18.092419  15.837257  229.124914
 Utah             2.134152   2.283533   1.998898   28.918980
 Vermont          0.630829   0.674984   0.590849    8.548090
 Virginia         8.286519   8.866537   7.761352  112.287064
 Washington       5.915014   6.329038   5.540144   80.151819
 West Virginia    1.195142   1.278797   1.119399   16.194858
 Wisconsin       11.943001  12.778955  11.186100  161.834472
 Wyoming          0.199766   0.213749   0.187106    2.706946

 [50 rows x 37 columns],
 np.float64(2.0):                        1         2         3         4          5   \
 Alabama          8.075171  0.373557  2.409301  0.037562   3.999616
 Alaska           0.020924  0.000968  0.006243  0.000097   0.010364
 Arizona          0.578733  0.026772  0.172670  0.002692   0.286645
 Arkansas         1.329560  0.061505  0.396686  0.006184   0.658528
 California      22.569282  1.044054  6.733750  0.104981  11.178520
 Colorado         0.616850  0.028535  0.184043  0.002869   0.305524
 Connecticut      1.006780  0.046574  0.300382  0.004683   0.498656
 Delaware         0.238274  0.011023  0.071091  0.001108   0.118016
 Florida          3.745705  0.173276  1.117565  0.017423   1.855240
 Georgia         15.410872  0.712906  4.597973  0.071684   7.632974
 Hawaii           0.286122  0.013236  0.085367  0.001331   0.141716
 Idaho            0.140953  0.006520  0.042054  0.000656   0.069814
 Illinois         2.364398  0.109377  0.705439  0.010998   1.171081
 Indiana          1.264520  0.058497  0.377281  0.005882   0.626314
 Iowa             0.724877  0.033533  0.216274  0.003372   0.359030
 Kansas           0.544183  0.025174  0.162362  0.002531   0.269533
 Kentucky         2.542164  0.117600  0.758478  0.011825   1.259129
 Louisiana        1.029327  0.047617  0.307109  0.004788   0.509823
 Maine            1.813407  0.083888  0.541046  0.008435   0.898177
 Maryland         1.188283  0.054970  0.354535  0.005527   0.588554
 Massachusetts    3.517320  0.162711  1.049424  0.016361   1.742121
 Michigan         1.390387  0.064319  0.414834  0.006467   0.688656
 Minnesota        0.865342  0.040031  0.258183  0.004025   0.428602
 Mississippi      2.348666  0.108649  0.700746  0.010925   1.163289
 Missouri         2.266923  0.104868  0.676357  0.010545   1.122802
 Montana          0.130572  0.006040  0.038957  0.000607   0.064672
 Nebraska         0.233246  0.010790  0.069591  0.001085   0.115526
 Nevada           0.212483  0.009829  0.063396  0.000988   0.105242
 New Hampshire    0.734445  0.033975  0.219128  0.003416   0.363769
 New Jersey       4.835201  0.223676  1.442626  0.022491   2.394865
 New Mexico       0.149225  0.006903  0.044523  0.000694   0.073911
 New York        13.582699  0.628335  4.052521  0.063180   6.727484
 North Carolina  23.713930  1.097005  7.075266  0.110305  11.745462
 North Dakota     0.053688  0.002484  0.016018  0.000250   0.026592
 Ohio             2.354990  0.108942  0.702633  0.010954   1.166422
 Oklahoma         0.775969  0.035896  0.231517  0.003609   0.384336
 Oregon           1.071012  0.049545  0.319546  0.004982   0.530470
 Pennsylvania     7.615816  0.352307  2.272248  0.035425   3.772098
 Rhode Island     1.015864  0.046994  0.303092  0.004725   0.503155
 South Carolina  12.132637  0.561255  3.619882  0.056435   6.009271
 South Dakota     0.125706  0.005815  0.037505  0.000585   0.062262
 Tennessee        6.125835  0.283381  1.827698  0.028494   3.034114
 Texas            6.499889  0.300684  1.939301  0.030234   3.219382
 Utah             0.411990  0.019059  0.122921  0.001916   0.204058
 Vermont          0.254006  0.011750  0.075785  0.001182   0.125808
 Virginia         5.553114  0.256887  1.656822  0.025830   2.750446
 Washington       1.090801  0.050460  0.325450  0.005074   0.540272
 West Virginia    0.379388  0.017550  0.113194  0.001765   0.187910
 Wisconsin        1.666127  0.077075  0.497104  0.007750   0.825229
 Wyoming          0.055635  0.002574  0.016599  0.000259   0.027556

                         6          7         8         9         10  ...  \
 Alabama          69.158765  15.021916  0.002534  0.498425  0.216558  ...
 Alaska            0.179200   0.038924  0.000007  0.001291  0.000561  ...
 Arizona           4.956480   1.076593  0.000182  0.035721  0.015520  ...
 Arkansas         11.386847   2.473327  0.000417  0.082065  0.035656  ...
 California      193.291709  41.984727  0.007083  1.393048  0.605257  ...
 Colorado          5.282930   1.147501  0.000194  0.038074  0.016543  ...
 Connecticut       8.622442   1.872873  0.000316  0.062142  0.027000  ...
 Delaware          2.040664   0.443251  0.000075  0.014707  0.006390  ...
 Florida          32.079612   6.967985  0.001176  0.231197  0.100451  ...
 Georgia         131.984429  28.668225  0.004837  0.951208  0.413284  ...
 Hawaii            2.450459   0.532262  0.000090  0.017660  0.007673  ...
 Idaho             1.207170   0.262208  0.000044  0.008700  0.003780  ...
 Illinois         20.249578   4.398394  0.000742  0.145938  0.063408  ...
 Indiana          10.829815   2.352335  0.000397  0.078050  0.033912  ...
 Iowa              6.208113   1.348459  0.000227  0.044742  0.019440  ...
 Kansas            4.660589   1.012323  0.000171  0.033589  0.014594  ...
 Kentucky         21.772038   4.729086  0.000798  0.156910  0.068175  ...
 Louisiana         8.815535   1.914815  0.000323  0.063533  0.027604  ...
 Maine            15.530688   3.373408  0.000569  0.111929  0.048631  ...
 Maryland         10.176897   2.210515  0.000373  0.073345  0.031867  ...
 Massachusetts    30.123633   6.543128  0.001104  0.217100  0.094326  ...
 Michigan         11.907788   2.586480  0.000436  0.085819  0.037287  ...
 Minnesota         7.411113   1.609762  0.000272  0.053412  0.023207  ...
 Mississippi      20.114844   4.369128  0.000737  0.144967  0.062986  ...
 Missouri         19.414768   4.217065  0.000711  0.139922  0.060794  ...

In [429]:
country_to_state_sector_matrices

{np.float64(1.0):       Alabama     Alaska    Arizona    Arkansas  California   Colorado  \
 1    5.017736   0.718687   1.734182    7.419288   27.086094   3.612112
 2    0.560379   0.080263   0.193673    0.828584    3.024968   0.403400
 3    2.335270   0.334479   0.807094    3.452960   12.605951   1.681088
 4    0.082526   0.011820   0.028522    0.122024    0.445483   0.059408
 5   10.211646   1.462607   3.529252   15.099071   55.123192   7.351047
 6   65.125783   9.327918  22.508156   96.295819  351.553607  46.882031
 7   16.784079   2.403971   5.800754   24.817155   90.601654  12.082338
 8    0.002637   0.000378   0.000911    0.003899    0.014236   0.001898
 9    0.398857   0.057128   0.137849    0.589755    2.153058   0.287125
 10   1.271445   0.182108   0.439425    1.879975    6.863352   0.915274
 11   0.068058   0.009748   0.023522    0.100632    0.367383   0.048993
 12   0.258014   0.036955   0.089172    0.381503    1.392778   0.185736
 13   2.793567   0.400120   0.965486    4.130603   15.079871   2.011002
 14  11.185396   1.602076   3.865790   16.538870   60.379561   8.052019
 15   0.036821   0.005274   0.012726    0.054443    0.198760   0.026506
 16   0.434882   0.062288   0.150300    0.643022    2.347525   0.313058
 17  16.051221   2.299005   5.547471   23.733541   86.645631  11.554776
 18  14.809794   2.121196   5.118421   21.897951   79.944320  10.661111
 19   2.627694   0.376363   0.908159    3.885342   14.184480   1.891596
 20  38.357087   5.493857  13.256613   56.715281  207.054281  27.612077
 21   2.340106   0.335172   0.808765    3.460111   12.632061   1.684570
 22   0.183646   0.026304   0.063470    0.271542    0.991335   0.132201
 23  17.762392   2.544094   6.138870   26.263701   95.882656  12.786595
 24   4.295257   0.615207   1.484486    6.351023   23.186105   3.092023
 25   0.588046   0.084225   0.203235    0.869492    3.174314   0.423316
 26   0.045564   0.006526   0.015747    0.067372    0.245959   0.032800
 27   0.100047   0.014330   0.034577    0.147930    0.540059   0.072020
 28   0.045090   0.006458   0.015584    0.066670    0.243398   0.032459
 29   2.942205   0.421410   1.016857    4.350382   15.882231   2.118002
 30   0.003632   0.000520   0.001255    0.005370    0.019605   0.002614
 31   0.009273   0.001328   0.003205    0.013711    0.050057   0.006675
 32   0.729168   0.104438   0.252008    1.078157    3.936100   0.524905
 33   0.391292   0.056045   0.135235    0.578570    2.112224   0.281679
 34   0.582394   0.083416   0.201282    0.861135    3.143805   0.419247
 35   1.141647   0.163517   0.394565    1.688054    6.162694   0.821837
 36   7.790894   1.115884   2.692615   11.519717   42.055802   5.608423
 37  72.999595  10.455678  25.229428  107.938138  394.057002  52.550144

     Connecticut   Delaware     Florida     Georgia  ...  South Dakota  \
 1      1.721675   1.065896    7.594760   10.341803  ...      1.078218
 2      0.192276   0.119039    0.848181    1.154970  ...      0.120415
 3      0.801273   0.496071    3.534625    4.813107  ...      0.501806
 4      0.028316   0.017531    0.124910    0.170091  ...      0.017733
 5      3.503800   2.169216   15.456175   21.046711  ...      2.194292
 6     22.345828  13.834391   98.573283  134.227478  ...     13.994315
 7      5.758920   3.565370   25.404099   34.592822  ...      3.606585
 8      0.000905   0.000560    0.003992    0.005435  ...      0.000567
 9      0.136855   0.084727    0.603703    0.822064  ...      0.085707
 10     0.436256   0.270088    1.924438    2.620512  ...      0.273210
 11     0.023352   0.014457    0.103012    0.140271  ...      0.014624
 12     0.088529   0.054809    0.390526    0.531780  ...      0.055442
 13     0.958523   0.593425    4.228295    5.757680  ...      0.600285
 14     3.837911   2.376066   16.930025   23.053657  ...      2.403533
 15     0.012634   0.007822    0.055731    0.075889  ...      0.007912
 16     0.149216   0.092380    0.658230    0.896314  ...      0.093448
 17     5.507463   3.409692   24.294856   33.082365  ...      3.449108
 18     5.081507   3.145981   22.415853   30.523722  ...      3.182348
 19     0.901609   0.558190    3.977234    5.415809  ...      0.564642
 20    13.161007   8.148032   58.056637   79.055864  ...      8.242222
 21     0.802933   0.497099    3.541945    4.823076  ...      0.502845
 22     0.063012   0.039011    0.277964    0.378504  ...      0.039462
 23     6.094596   3.773189   26.884856   36.609174  ...      3.816806
 24     1.473780   0.912423    6.501229    8.852739  ...      0.922971
 25     0.201769   0.124916    0.890056    1.211992  ...      0.126360
 26     0.015634   0.009679    0.068965    0.093910  ...      0.009791
 27     0.034328   0.021252    0.151429    0.206201  ...      0.021498
 28     0.015471   0.009578    0.068247    0.092932  ...      0.009689
 29     1.009523   0.625000    4.453272    6.064031  ...      0.632225
 30     0.001246   0.000772    0.005497    0.007486  ...      0.000780
 31     0.003182   0.001970    0.014036    0.019113  ...      0.001993
 32     0.250191   0.154894    1.103656    1.502851  ...      0.156685
 33     0.134259   0.083121    0.592254    0.806473  ...      0.084081
 34     0.199830   0.123715    0.881502    1.200343  ...      0.125146
 35     0.391720   0.242515    1.727978    2.352992  ...      0.245319
 36     2.673196   1.654986   11.792166   16.057421  ...      1.674118
 37    25.047475  15.506991  110.490951  150.455796  ...     15.686250

     Tennessee       Texas       Utah   Vermont    Virginia  Washington  \
 1    5.917137   14.615494   1.844693  0.545268    7.162603    5.112750
 2    0.660824    1.632255   0.206015  0.060895    0.799918    0.570991
 3    2.753854    6.802096   0.858526  0.253770    3.333498    2.379490
 4    0.097319    0.240380   0.030340  0.008968    0.117803    0.084089
 5   12.042028   29.744144   3.754154  1.109681   14.576689   10.405011
 6   76.799225  189.696219  23.942491  7.077102   92.964275   66.358986
 7   19.792534   48.888109   6.170408  1.823896   23.958557   17.101898
 8    0.003110    0.007682   0.000970  0.000287    0.003765    0.002687
 9    0.470350    1.161777   0.146634  0.043343    0.569351    0.406409
 10   1.499345    3.703424   0.467427  0.138166    1.814934    1.295521
 11   0.080257    0.198237   0.025021  0.007396    0.097150    0.069347
 12   0.304262    0.751535   0.094855  0.028038    0.368304    0.262900
 13   3.294298    8.137008   1.027012  0.303572    3.987697    2.846465
 14  13.190317   32.580449   4.112138  1.215497   15.966675   11.397199
 15   0.043420    0.107250   0.013537  0.004001    0.052560    0.037518
 16   0.512832    1.266710   0.159878  0.047258    0.620776    0.443117
 17  18.928315   46.753463   5.900984  1.744257   22.912433   16.355162
 18  17.464369   43.137476   5.444593  1.609354   21.140349   15.090228
 19   3.098694    7.653861   0.966031  0.285547    3.750921    2.677452
 20  45.232386  111.725249  14.101392  4.168196   54.753104   39.083406
 21   2.759558    6.816184   0.860304  0.254295    3.340402    2.384418
 22   0.216564    0.534918   0.067515  0.019956    0.262147    0.187124
 23  20.946204   51.737706   6.530070  1.930207   25.355056   18.098736
 24   5.065159   12.511083   1.579085  0.466758    6.131297    4.376591
 25   0.693450    1.712841   0.216186  0.063902    0.839410    0.599181
 26   0.053731    0.132718   0.016751  0.004951    0.065041    0.046427
 27   0.117979    0.291412   0.036781  0.010872    0.142812    0.101941
 28   0.053172    0.131336   0.016577  0.004900    0.064364    0.045944
 29   3.469579    8.569957   1.081656  0.319724    4.199872    2.997918
 30   0.004283    0.010579   0.001335  0.000395    0.005184    0.003701
 31   0.010935    0.027011   0.003409  0.001008    0.013237    0.009449
 32   0.859867    2.123896   0.268067  0.079237    1.040856    0.742975
 33   0.461429    1.139744   0.143853  0.042521    0.558553    0.398702
 34   0.686785    1.696378   0.214108  0.063288    0.831343    0.593422
 35   1.346281    3.325353   0.419709  0.124061    1.629653    1.163265
 36   9.187370   22.693059   2.864202  0.846623   11.121169    7.938421
 37  86.084374  212.630796  26.837177  7.932735  104.203805   74.381894

     West Virginia   Wisconsin   Wyoming
 1        1.033043   10.323149  0.172672
 2        0.115370    1.152887  0.019284
 3        0.480781    4.804426  0.080362
 4        0.016990    0.169784  0.002840
 5        2.102356   21.008749  0.351406
 6       13.407985  133.985375  2.241125
 7        3.455478   34.530428  0.577578
 8        0.000543    0.005426  0.000091
 9        0.082116    0.820581  0.013726
 10       0.261763    2.615785  0.043753
 11       0.014012    0.140018  0.002342
 12       0.053119    0.530821  0.008879
 13       0.575135    5.747295  0.096133
 14       2.302830   23.012075  0.384915
 15       0.007581    0.075752  0.001267
 16       0.089533    0.894697  0.014965
 17       3.304598   33.022695  0.552359
 18       3.049015   30.468667  0.509638
 19       0.540985    5.406040  0.090425
 20       7.896891   78.913272  1.319954
 21       0.481777    4.814376  0.080528
 22       0.037809    0.377821  0.006320
 23       3.656891   36.543143  0.611244
 24       0.884300    8.836772  0.147809
 25       0.121066    1.209806  0.020236
 26       0.009381    0.093741  0.001568
 27       0.020597    0.205829  0.003443
 28       0.009283    0.092765  0.001552
 29       0.605736    6.053093  0.101248
 30       0.000748    0.007472  0.000125
 31       0.001909    0.019078  0.000319
 32       0.150120    1.500140  0.025092
 33       0.080559    0.805019  0.013465
 34       0.119902    1.198178  0.020041
 35       0.235040    2.348748  0.039287
 36       1.603976   16.028458  0.268102
 37      15.029031  150.184422  2.512080

 [37 rows x 50 columns],
 np.float64(2.0):        Alabama        Alaska       Arizona   Arkansas  California  \
 1     2.797952  7.249897e-03  2.005241e-01   0.460677    7.819992
 2     1.627427  4.216896e-03  1.166346e-01   0.267952    4.548492
 3     3.732703  9.671971e-03  2.675159e-01   0.614582   10.432525
 4     0.062224  1.612306e-04  4.459458e-03   0.010245    0.173909
 5    22.361767  5.794256e-02  1.602626e+00   3.681819   62.498863
 6    67.150347  1.739962e-01  4.812541e+00  11.056165  187.678385
 7   148.911046  3.858499e-01  1.067218e+01  24.517894  416.191217
 8     0.000007  1.765214e-08  4.882384e-07   0.000001    0.000019
 9     1.498586  3.883051e-03  1.074009e-01   0.246739    4.188394
 10    0.433572  1.123446e-03  3.107327e-02   0.071387    1.211788
 11    0.036446  9.443578e-05  2.611988e-03   0.006001    0.101862
 12    0.753955  1.953605e-03  5.403452e-02   0.124137    2.107226
 13    7.451502  1.930791e-02  5.340353e-01   1.226874   20.826190
 14   18.465932  4.784789e-02  1.323419e+00   3.040377   51.610400
 15    0.055671  1.442527e-04  3.989868e-03   0.009166    0.155596
 16    0.599172  1.552541e-03  4.294156e-02   0.098652    1.674625
 17   47.372614  1.227493e-01  3.395107e+00   7.799803  132.401635
 18    8.815569  2.284241e-02  6.317955e-01   1.451465   24.638619
 19   33.441716  8.665230e-02  2.396706e+00   5.506109   93.466193
 20    0.663493  1.719207e-03  4.755134e-02   0.109243    1.854396
 21   20.429368  5.293543e-02  1.464135e+00   3.363653   57.098005
 22    0.109687  2.842158e-04  7.861090e-03   0.018060    0.306565
 23   59.338315  1.537541e-01  4.252667e+00   9.769930  165.844549
 24    1.926516  4.991881e-03  1.380698e-01   0.317197    5.384417
 25    1.091051  2.827069e-03  7.819357e-02   0.179639    3.049375
 26    2.647298  6.859529e-03  1.897269e-01   0.435872    7.398927
 27    0.158281  4.101280e-04  1.134368e-02   0.026061    0.442378
 28    0.054830  1.420712e-04  3.929531e-03   0.009028    0.153243
 29    3.561046  9.227183e-03  2.552136e-01   0.586319    9.952762
 30    0.136654  3.540900e-04  9.793734e-03   0.022500    0.381934
 31    0.198818  5.151659e-04  1.424891e-02   0.032735    0.555676
 32   70.221015  1.819528e-01  5.032610e+00  11.561744  196.260588
 33    0.931000  2.412355e-03  6.672304e-02   0.153287    2.602050
 34   27.906798  7.231053e-02  2.000028e+00   4.594796   77.996660
 35   28.074796  7.274584e-02  2.012069e+00   4.622457   78.466197
 36    7.749611  2.008036e-02  5.554002e-01   1.275957   21.659373
 37  112.924860  2.926046e-01  8.093115e+00  18.592844  315.613490

         Colorado   Connecticut      Delaware    Florida     Georgia  ...  \
 1   2.137312e-01  3.488376e-01  8.255903e-02   1.297843    5.339687  ...
 2   1.243166e-01  2.029011e-01  4.802039e-02   0.754889    3.105824  ...
 3   2.851354e-01  4.653787e-01  1.101407e-01   1.731432    7.123590  ...
 4   4.753172e-03  7.757806e-03  1.836032e-03   0.028863    0.118749  ...
 5   1.708180e+00  2.787977e+00  6.598274e-01  10.372609   42.675792  ...
 6   5.129510e+00  8.372040e+00  1.981402e+00  31.147998  128.151510  ...
 7   1.137508e+01  1.856564e+01  4.393910e+00  69.073075  284.185806  ...
 8   5.203953e-07  8.493541e-07  2.010157e-07   0.000003    0.000013  ...
 9   1.144746e-01  1.868377e-01  4.421868e-02   0.695126    2.859941  ...
 10  3.311986e-02  5.405599e-02  1.279337e-02   0.201114    0.827440  ...
 11  2.784022e-03  4.543893e-03  1.075398e-03   0.016905    0.069554  ...
 12  5.759341e-02  9.400007e-02  2.224689e-02   0.349725    1.438867  ...
 13  5.692086e-01  9.290239e-01  2.198711e-01   3.456414   14.220645  ...
 14  1.410584e+00  2.302259e+00  5.448732e-01   8.565508   35.240876  ...
 15  4.252653e-03  6.940894e-03  1.642694e-03   0.025823    0.106245  ...
 16  4.576983e-02  7.470242e-02  1.767974e-02   0.277929    1.143476  ...
 17  3.618720e+00  5.906230e+00  1.397821e+00  21.974006   90.407159  ...
 18  6.734076e-01  1.099090e+00  2.601205e-01   4.089142   16.823867  ...
 19  2.554560e+00  4.169381e+00  9.867629e-01  15.512094   63.821062  ...
 20  5.068322e-02  8.272173e-02  1.957766e-02   0.307764    1.266228  ...
 21  1.560568e+00  2.547053e+00  6.028082e-01   9.476257   38.987951  ...
 22  8.378847e-03  1.367539e-02  3.236539e-03   0.050879    0.209330  ...
 23  4.532761e+00  7.398067e+00  1.750892e+00  27.524351  113.242819  ...
 24  1.471636e-01  2.401904e-01  5.684561e-02   0.893623    3.676615  ...
 25  8.334365e-02  1.360279e-01  3.219357e-02   0.506089    2.082190  ...
 26  2.022229e-01  3.300546e-01  7.811367e-02   1.227961    5.052173  ...
 27  1.209081e-02  1.973381e-02  4.670379e-03   0.073419    0.302067  ...
 28  4.188342e-03  6.835929e-03  1.617852e-03   0.025433    0.104638  ...
 29  2.720228e-01  4.439772e-01  1.050756e-01   1.651808    6.795996  ...
 30  1.043878e-02  1.703747e-02  4.032240e-03   0.063388    0.260794  ...
 31  1.518739e-02  2.478784e-02  5.866510e-03   0.092223    0.379429  ...
 32  5.364074e+00  8.754879e+00  2.072008e+00  32.572341  134.011654  ...
 33  7.111763e-02  1.160734e-01  2.747096e-02   0.431849    1.776745  ...
 34  2.131757e+00  3.479309e+00  8.234444e-01  12.944697   53.258077  ...
 35  2.144590e+00  3.500255e+00  8.284015e-01  13.022624   53.578688  ...
 36  5.919806e-01  9.661909e-01  2.286673e-01   3.594693   14.789563  ...
 37  8.626154e+00  1.407903e+01  3.332068e+00  52.380717  215.508810  ...

     South Dakota   Tennessee       Texas          Utah       Vermont  \
 1   4.355556e-02    2.122530    2.252135  1.427495e-01  8.800997e-02
 2   2.533405e-02    1.234568    1.309953  8.303015e-02  5.119092e-02
 3   5.810677e-02    2.831633    3.004537  1.904399e-01  1.174127e-01
 4   9.686327e-04    0.047203    0.050085  3.174609e-03  1.957255e-03
 5   3.481043e-01   16.963664   17.999494  1.140882e+00  7.033924e-01
 6   1.045325e+00   50.940336   54.050838  3.425963e+00  2.112223e+00
 7   2.318089e+00  112.964103  119.861880  7.597336e+00  4.684017e+00
 8   1.060496e-07    0.000005    0.000005  3.475683e-07  2.142877e-07
 9   2.332839e-02    1.136829    1.206246  7.645678e-02  4.713821e-02
 10  6.749383e-03    0.328908    0.348992  2.212052e-02  1.363805e-02
 11  5.673464e-04    0.027648    0.029336  1.859428e-03  1.146401e-03
 12  1.173676e-02    0.571951    0.606875  3.846622e-02  2.371574e-02
 13  1.159971e-01    5.652719    5.997883  3.801704e-01  2.343880e-01
 14  2.874581e-01   14.008279   14.863648  9.421188e-01  5.808484e-01
 15  8.666338e-04    0.042232    0.044811  2.840317e-03  1.751152e-03
 16  9.327277e-03    0.454533    0.482287  3.056934e-02  1.884704e-02
 17  7.374467e-01   35.936924   38.131292  2.416917e+00  1.490112e+00
 18  1.372314e-01    6.687502    7.095852  4.497641e-01  2.772949e-01
 19  5.205852e-01   25.368927   26.917996  1.706173e+00  1.051914e+00
 20  1.032856e-02    0.503327    0.534061  3.385096e-02  2.087027e-02
 21  3.180228e-01   15.497744   16.444062  1.042292e+00  6.426085e-01
 22  1.707497e-03    0.083209    0.088290  5.596172e-03  3.450231e-03
 23  9.237160e-01   45.014119   47.762756  3.027399e+00  1.866495e+00
 24  2.998996e-02    1.461458    1.550697  9.828949e-02  6.059883e-02
 25  1.698432e-02    0.827672    0.878211  5.566463e-02  3.431914e-02
 26  4.121032e-02    2.008243    2.130870  1.350632e-01  8.327111e-02
 27  2.463946e-03    0.120072    0.127404  8.075367e-03  4.978740e-03
 28  8.535280e-04    0.041594    0.044134  2.797364e-03  1.724670e-03
 29  5.543459e-02    2.701414    2.866367  1.816821e-01  1.120132e-01
 30  2.127284e-03    0.103666    0.109996  6.971987e-03  4.298468e-03
 31  3.094987e-03    0.150824    0.160033  1.014355e-02  6.253845e-03
 32  1.093126e+00   53.269748   56.522488  3.582626e+00  2.208812e+00
 33  1.449282e-02    0.706258    0.749383  4.749896e-02  2.928473e-02
 34  4.344235e-01   21.170132   22.462815  1.423785e+00  8.778121e-01
 35  4.370387e-01   21.297575   22.598040  1.432356e+00  8.830965e-01
 36  1.206377e-01    5.878864    6.237837  3.953796e-01  2.437651e-01
 37  1.757895e+00   85.664938   90.895782  5.761346e+00  3.552067e+00

       Virginia    Washington  West Virginia  Wisconsin       Wyoming
 1     1.924089  3.779499e-01   1.314534e-01   0.577293  1.927686e-02
 2     1.119145  2.198343e-01   7.645974e-02   0.335782  1.121237e-02
 3     2.566896  5.042169e-01   1.753698e-01   0.770158  2.571695e-02
 4     0.042790  8.405235e-03   2.923394e-03   0.012838  4.286985e-04
 5    15.377685  3.020648e+00   1.050600e+00   4.613839  1.540644e-01
 6    46.177787  9.070730e+00   3.154857e+00  13.854938  4.626412e-01
 7   102.402784  2.011504e+01   6.996137e+00  30.724388  1.025942e+00
 8     0.000005  9.202371e-07   3.200642e-07   0.000001  4.693554e-08
 9     1.030544  2.024303e-01   7.040654e-02   0.309199  1.032470e-02
 10    0.298157  5.856724e-02   2.037006e-02   0.089458  2.987149e-03
 11    0.025063  4.923104e-03   1.712287e-03   0.007520  2.510967e-04
 12    0.518478  1.018449e-01   3.542228e-02   0.155561  5.194470e-03
 13    5.124231  1.006556e+00   3.500864e-01   1.537447  5.133811e-02
 14   12.698607  2.494395e+00   8.675662e-01   3.810023  1.272235e-01
 15    0.038284  7.520147e-03   2.615554e-03   0.011487  3.835557e-04
 16    0.412037  8.093672e-02   2.815030e-02   0.123625  4.128076e-03
 17   32.577084  6.399136e+00   2.225660e+00   9.774255  3.263799e-01
 18    6.062269  1.190815e+00   4.141730e-01   1.818891  6.073603e-02
 19   22.997118  4.517337e+00   1.571158e+00   6.899933  2.304011e-01
 20    0.456269  8.962528e-02   3.117224e-02   0.136897  4.571225e-03
 21   14.048818  2.759618e+00   9.598124e-01   4.215133  1.407508e-01
 22    0.075430  1.481667e-02   5.153331e-03   0.022631  7.557057e-04
 23   40.805627  8.015473e+00   2.787832e+00  12.243104  4.088192e-01
 24    1.324822  2.602356e-01   9.051157e-02   0.397493  1.327299e-02
 25    0.750291  1.473801e-01   5.125972e-02   0.225113  7.516937e-03
 26    1.820487  3.575994e-01   1.243753e-01   0.546209  1.823891e-02
 27    0.108846  2.138070e-02   7.436340e-03   0.032658  1.090496e-03
 28    0.037705  7.406422e-03   2.576000e-03   0.011313  3.777553e-04
 29    2.448852  4.810293e-01   1.673050e-01   0.734740  2.453430e-02
 30    0.093974  1.845934e-02   6.420274e-03   0.028195  9.414954e-04

# Gross Output

In [505]:

# A is your 1914x87 matrix
# Reshape A into 22 blocks of 87x87
blocks = final_matrix.reshape(22, 87, 87)

# For each block (each submatrix), sum across the columns (axis=2)
# This gives you an array of shape (22, 87)
row_sums = np.sum(blocks, axis=2)

# Transpose to get a final matrix of shape (87, 22)
GO = row_sums.T

In [509]:
df = pd.DataFrame(GO)

# Save to CSV
df.to_csv(out_folder_GO + "GO.csv",
          index=False,  # Set to True if you want row indices
          header=False)